In [1]:
# ============================================================
# Cell 1: Kaggle Save & Run compatibility setup
# ============================================================

import os
import sys
import subprocess

# Force CPU for the full notebook.
os.environ["CUDA_VISIBLE_DEVICES"] = ""

# Remove torchvision because it can break transformers import in this Kaggle environment.
subprocess.run(
    [sys.executable, "-m", "pip", "uninstall", "-y", "torchvision"],
    check=False
)

print("Setup complete. Running notebook in CPU-safe mode.")

Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Setup complete. Running notebook in CPU-safe mode.

In [2]:
# ============================================================
# Cell 2: Imports and paths
# ============================================================

import os, re, json, time, zipfile, urllib.request, warnings
from pathlib import Path
from datetime import datetime

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, precision_recall_curve
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

import torch
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM

BASE_DIR = "/kaggle/working/maintenance_wizard"
DOC_DIR = f"{BASE_DIR}/docs"
DATA_DIR = f"{BASE_DIR}/data"
PUBLIC_DIR = f"{BASE_DIR}/public_datasets"
REPORT_DIR = f"{BASE_DIR}/reports"

for d in [DOC_DIR, DATA_DIR, PUBLIC_DIR, REPORT_DIR]:
    os.makedirs(d, exist_ok=True)

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("torch:", torch.__version__)
print("GPU visible:", torch.cuda.is_available())
print("BASE_DIR:", BASE_DIR)

numpy: 2.4.6
pandas: 2.3.3
torch: 2.10.0+cu128
GPU visible: False
BASE_DIR: /kaggle/working/maintenance_wizard

In [3]:
# ============================================================
# Cell 3: Steel maintenance demo data + knowledge base
# ============================================================

import os
import json
import numpy as np
import pandas as pd

os.makedirs(DOC_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)

rng = np.random.default_rng(42)

ASSETS = [
    {
        "asset_id": "MTR-204",
        "asset_type": "Induction Motor",
        "area": "Hot Strip Mill",
        "criticality": "High",
        "criticality_score": 3,
        "main_issue": "overheating and high current",
    },
    {
        "asset_id": "GBX-17",
        "asset_type": "Gearbox",
        "area": "Finishing Mill",
        "criticality": "Critical",
        "criticality_score": 4,
        "main_issue": "abnormal vibration and bearing wear",
    },
    {
        "asset_id": "PMP-09",
        "asset_type": "Cooling Water Pump",
        "area": "Caster Utility",
        "criticality": "High",
        "criticality_score": 3,
        "main_issue": "cavitation and low suction pressure",
    },
    {
        "asset_id": "HPP-12",
        "asset_type": "Hydraulic Power Pack",
        "area": "Plate Mill",
        "criticality": "Medium",
        "criticality_score": 2,
        "main_issue": "low hydraulic pressure and leakage risk",
    },
]

asset_master = pd.DataFrame(ASSETS)
asset_master.to_csv(f"{DATA_DIR}/asset_master.csv", index=False)

periods = 720
end_ts = pd.Timestamp.now().floor("h")
timestamps = pd.date_range(end=end_ts, periods=periods, freq="h")

def ramp(periods, start, end_value=1.0):
    x = np.zeros(periods)
    if start < periods:
        x[start:] = np.linspace(0, end_value, periods - start)
    return x

sensor_rows = []

for asset in ASSETS:
    aid = asset["asset_id"]
    stage = ramp(periods, 470, 1.0)

    for i, ts in enumerate(timestamps):
        s = stage[i]

        if aid == "MTR-204":
            temperature = 58 + 30 * s + rng.normal(0, 1.6)
            vibration = 2.2 + 3.6 * s + rng.normal(0, 0.25)
            current = 48 + 34 * s + rng.normal(0, 2.0)
            pressure = 9.5 + rng.normal(0, 0.25)
            rpm = 1480 - 55 * s + rng.normal(0, 8)
            alarm_count = int(temperature > 78) + int(current > 75) + int(vibration > 5.0)
            failure_label = int(temperature > 84 and current > 78)

        elif aid == "GBX-17":
            temperature = 52 + 18 * s + rng.normal(0, 1.4)
            vibration = 3.0 + 8.2 * s + rng.normal(0, 0.35)
            current = 42 + 14 * s + rng.normal(0, 1.8)
            pressure = 10.0 + rng.normal(0, 0.2)
            rpm = 980 - 35 * s + rng.normal(0, 6)
            alarm_count = int(vibration > 7.0) + int(vibration > 9.0) + int(temperature > 65)
            failure_label = int(vibration > 9.3)

        elif aid == "PMP-09":
            temperature = 49 + 13 * s + rng.normal(0, 1.2)
            vibration = 2.5 + 4.2 * s + rng.normal(0, 0.3)
            current = 38 + 23 * s + rng.normal(0, 2.0)
            pressure = 9.2 - 4.8 * s + rng.normal(0, 0.25)
            rpm = 1440 - 70 * s + rng.normal(0, 10)
            alarm_count = int(pressure < 6.2) + int(vibration > 5.3) + int(current > 58)
            failure_label = int(pressure < 5.7 and vibration > 5.1)

        else:
            temperature = 46 + 22 * s + rng.normal(0, 1.5)
            vibration = 1.8 + 2.5 * s + rng.normal(0, 0.25)
            current = 34 + 14 * s + rng.normal(0, 1.7)
            pressure = 10.5 - 5.4 * s + rng.normal(0, 0.3)
            rpm = 1200 + rng.normal(0, 5)
            alarm_count = int(pressure < 6.4) + int(temperature > 62) + int(pressure < 5.6)
            failure_label = int(pressure < 5.5)

        sensor_rows.append({
            "source": "steel_demo_app",
            "timestamp": ts.strftime("%Y-%m-%d %H:%M:%S"),
            "asset_id": aid,
            "asset_type": asset["asset_type"],
            "area": asset["area"],
            "criticality": asset["criticality"],
            "criticality_score": asset["criticality_score"],
            "temperature": round(float(temperature), 3),
            "vibration": round(float(vibration), 3),
            "current": round(float(current), 3),
            "pressure": round(float(pressure), 3),
            "rpm": round(float(rpm), 3),
            "alarm_count": int(alarm_count),
            "delay_hours": round(float(max(0, alarm_count * 1.5 + s * 4)), 2),
            "spare_lead_time_days": int(2 + asset["criticality_score"] + alarm_count),
            "failure_label": int(failure_label),
            "failure_mode": asset["main_issue"] if failure_label else "normal",
        })

steel_df = pd.DataFrame(sensor_rows)
steel_df.to_csv(f"{DATA_DIR}/steel_sensor_logs.csv", index=False)

maintenance_history = pd.DataFrame([
    ["WO-1001", "MTR-204", "2026-05-02 09:30:00", "Motor temperature rising", "Cleaned cooling fins and checked bearing grease", "Temporary improvement", 2.0],
    ["WO-1002", "GBX-17", "2026-05-08 14:00:00", "Gearbox vibration above warning", "Oil sample collected, alignment checked", "Bearing wear suspected", 4.5],
    ["WO-1003", "PMP-09", "2026-05-14 11:15:00", "Pump cavitation noise", "Checked suction strainer and impeller clearance", "Suction restriction found", 3.0],
    ["WO-1004", "HPP-12", "2026-05-20 16:20:00", "Hydraulic pressure fluctuation", "Inspected relief valve and filter", "Filter choking observed", 2.5],
], columns=[
    "work_order_id", "asset_id", "timestamp", "issue", "action_taken", "result", "downtime_hours"
])
maintenance_history.to_csv(f"{DATA_DIR}/maintenance_history.csv", index=False)

failure_reports = pd.DataFrame([
    ["FR-201", "MTR-204", "2026-04-18 07:45:00", "Overheating", "Bearing lubrication degradation", "Regrease bearing, inspect load current, clean cooling path", "Line speed reduction for 3 hours"],
    ["FR-202", "GBX-17", "2026-04-26 18:10:00", "High vibration", "Bearing pitting and gear mesh misalignment", "Replace bearing set, verify coupling alignment", "Finishing mill delay risk"],
    ["FR-203", "PMP-09", "2026-05-04 10:40:00", "Cavitation", "Low suction head due to clogged strainer", "Clean strainer, inspect impeller erosion", "Cooling instability risk"],
    ["FR-204", "HPP-12", "2026-05-11 13:05:00", "Low pressure", "Hydraulic oil leakage and filter choking", "Replace filter, inspect seals, top up oil", "Actuator slow response"],
], columns=[
    "report_id", "asset_id", "timestamp", "failure_mode", "root_cause", "corrective_action", "business_impact"
])
failure_reports.to_csv(f"{DATA_DIR}/failure_reports.csv", index=False)

spares_inventory = pd.DataFrame([
    ["SP-001", "MTR-204", "DE bearing 6312", 2, 5, "Critical", 18000],
    ["SP-002", "MTR-204", "Cooling fan kit", 1, 7, "High", 12000],
    ["SP-003", "GBX-17", "Gearbox bearing set", 1, 12, "Critical", 85000],
    ["SP-004", "GBX-17", "Synthetic gear oil drum", 4, 2, "High", 15000],
    ["SP-005", "PMP-09", "Mechanical seal kit", 3, 4, "High", 22000],
    ["SP-006", "PMP-09", "Impeller assembly", 1, 10, "Critical", 65000],
    ["SP-007", "HPP-12", "Hydraulic filter element", 6, 3, "High", 8000],
    ["SP-008", "HPP-12", "Relief valve cartridge", 1, 9, "Critical", 32000],
], columns=[
    "spare_id", "asset_id", "spare_part", "stock_qty", "lead_time_days", "spare_criticality", "unit_cost_inr"
])
spares_inventory.to_csv(f"{DATA_DIR}/spares_inventory.csv", index=False)

delay_logs = pd.DataFrame([
    ["DL-301", "MTR-204", "Hot Strip Mill", 3.5, "Reduced motor load due to overheating"],
    ["DL-302", "GBX-17", "Finishing Mill", 8.0, "Gearbox vibration may stop finishing stand"],
    ["DL-303", "PMP-09", "Caster Utility", 5.0, "Cooling water instability can affect caster"],
    ["DL-304", "HPP-12", "Plate Mill", 4.0, "Hydraulic low pressure slows actuator cycle"],
], columns=[
    "delay_id", "asset_id", "area", "delay_hours", "delay_reason"
])
delay_logs.to_csv(f"{DATA_DIR}/delay_logs.csv", index=False)

incident_records = pd.DataFrame([
    ["INC-401", "MTR-204", "Temperature crossed high alarm during peak load", "High", "Inspect bearing and cooling path"],
    ["INC-402", "GBX-17", "Repeated vibration spikes during finishing load", "Critical", "Plan immediate vibration inspection"],
    ["INC-403", "PMP-09", "Cavitation noise reported by operator", "High", "Check suction strainer and pump inlet"],
    ["INC-404", "HPP-12", "Pressure recovery slow after valve actuation", "Medium", "Inspect filter and relief valve"],
], columns=[
    "incident_id", "asset_id", "incident_summary", "severity", "recommended_response"
])
incident_records.to_csv(f"{DATA_DIR}/incident_records.csv", index=False)

digital_logbook = pd.DataFrame([
    ["2026-06-01 08:00:00", "system", "MTR-204", "Initial condition review created", "Open"],
    ["2026-06-01 08:05:00", "system", "GBX-17", "Vibration watchlist created", "Open"],
    ["2026-06-01 08:10:00", "system", "PMP-09", "Cavitation watchlist created", "Open"],
    ["2026-06-01 08:15:00", "system", "HPP-12", "Pressure watchlist created", "Open"],
], columns=[
    "timestamp", "user", "asset_id", "log_entry", "status"
])
digital_logbook.to_csv(f"{DATA_DIR}/digital_logbook.csv", index=False)

feedback_log = pd.DataFrame(columns=[
    "timestamp", "user", "asset_id", "query", "recommendation",
    "engineer_feedback", "outcome"
])
feedback_log.to_csv(f"{DATA_DIR}/feedback_log.csv", index=False)

def write_doc(filename, text):
    with open(f"{DOC_DIR}/{filename}", "w", encoding="utf-8") as f:
        f.write(text.strip() + "\n")

write_doc("SOP_MTR_204_motor_overheating.txt", """
Asset MTR-204 induction motor SOP.
Symptoms: high winding temperature, rising current, vibration increase, repeated thermal alarms.
Likely root causes: bearing lubrication loss, blocked cooling fins, overloaded drive, rotor imbalance.
Inspection order: bearing temperature and grease condition, cooling fan, air path, current imbalance, coupling alignment.
Recommended action: reduce load if temperature exceeds 80 C, inspect lubrication, clean cooling path, plan bearing replacement if vibration exceeds 5 mm/s.
Required spares: DE bearing 6312, cooling fan kit, grease, current clamp meter.
""")

write_doc("SOP_GBX_17_gearbox_vibration.txt", """
Asset GBX-17 gearbox SOP.
Symptoms: vibration above 7 mm/s warning or above 9 mm/s critical, temperature rise, abnormal noise.
Likely root causes: bearing pitting, gear mesh wear, coupling misalignment, oil contamination.
Inspection order: vibration spectrum, oil sample, bearing temperature, coupling alignment, gear backlash.
Recommended action: if vibration exceeds 9 mm/s create P1 alert, prepare bearing set, inspect oil, schedule controlled shutdown.
Required spares: gearbox bearing set, synthetic gear oil, coupling shim pack.
""")

write_doc("SOP_PMP_09_cavitation.txt", """
Asset PMP-09 cooling water pump SOP.
Symptoms: low suction pressure, vibration increase, rattling sound, fluctuating discharge pressure.
Likely root causes: clogged suction strainer, low tank level, air ingress, impeller erosion.
Inspection order: suction strainer, tank level, inlet valve position, seal leakage, impeller condition.
Recommended action: clean strainer, verify suction head, inspect impeller and mechanical seal, monitor pressure recovery.
Required spares: mechanical seal kit, impeller assembly, suction gasket.
""")

write_doc("SOP_HPP_12_hydraulic_pressure.txt", """
Asset HPP-12 hydraulic power pack SOP.
Symptoms: low system pressure, slow actuator response, high oil temperature, pressure alarm.
Likely root causes: filter choking, relief valve leakage, pump wear, hydraulic oil leakage.
Inspection order: filter differential pressure, relief valve setting, oil level, pump noise, hose leakage.
Recommended action: replace filter, inspect relief valve cartridge, top up oil, plan pump inspection if pressure remains below limit.
Required spares: hydraulic filter element, relief valve cartridge, hydraulic oil.
""")

write_doc("maintenance_prioritization_policy.txt", """
Maintenance priority policy.
Prioritize by safety risk, asset criticality, failure risk, estimated RUL, production delay, spare availability, and repair lead time.
P1 Critical: high failure risk, low RUL, critical asset, production bottleneck, or safety risk.
P2 High: elevated failure risk or repeated alerts with meaningful production impact.
P3 Medium: warning condition that can be planned.
P4 Low: monitor only.
Always provide diagnosis, root cause, risk, RUL estimate, recommended repair plan, spares strategy, evidence sources, and alerting action.
""")

write_doc("feedback_learning_policy.txt", """
Feedback loop policy.
Engineer feedback must be stored in feedback_log.csv.
Accepted recommendations increase confidence for similar future cases.
Rejected recommendations must be used to revise action order and root cause ranking.
Digital maintenance logbook entries must be created for every agent recommendation and alert.
""")

print("Cell 3 complete")
print("Steel sensor rows:", steel_df.shape)
print("Files written to:", DATA_DIR)
print("Docs written to:", DOC_DIR)

Cell 3 complete
Steel sensor rows: (2880, 17)
Files written to: /kaggle/working/maintenance_wizard/data
Docs written to: /kaggle/working/maintenance_wizard/docs

In [4]:
# ============================================================
# Cell 3B: Public AI4I benchmark ingestion, leakage-safe converter
# Fixed:
# - AI4I UDI fillna bug
# - Recreates sensor_logs.csv compatibility file
# - Keeps AI4I benchmark separate from steel app decisions
# ============================================================

import os
import json
import zipfile
import urllib.request
import tempfile
import numpy as np
import pandas as pd

os.makedirs(PUBLIC_DIR, exist_ok=True)

PUBLIC_AI4I_URLS = [
    "https://archive.ics.uci.edu/ml/machine-learning-databases/00601/ai4i2020.csv",
    "https://archive.ics.uci.edu/static/public/601/ai4i+2020+predictive+maintenance+dataset.zip",
]

COMMON_COLUMNS = [
    "source", "timestamp", "asset_id", "asset_type", "area",
    "criticality", "criticality_score",
    "temperature", "vibration", "current", "pressure", "rpm",
    "alarm_count", "delay_hours", "spare_lead_time_days",
    "failure_label", "failure_mode"
]

def download_ai4i_dataset():
    last_error = None

    for url in PUBLIC_AI4I_URLS:
        try:
            if url.endswith(".csv"):
                df = pd.read_csv(url)
                return df, url

            tmp_path = tempfile.NamedTemporaryFile(delete=False, suffix=".zip").name
            urllib.request.urlretrieve(url, tmp_path)

            with zipfile.ZipFile(tmp_path, "r") as z:
                csv_names = [n for n in z.namelist() if n.lower().endswith(".csv")]
                if not csv_names:
                    raise ValueError("No CSV found inside AI4I zip")
                with z.open(csv_names[0]) as f:
                    df = pd.read_csv(f)

            return df, url

        except Exception as e:
            last_error = str(e)

    raise RuntimeError(f"Could not download AI4I dataset. Last error: {last_error}")

def convert_ai4i_to_common_schema(raw_df):
    """
    Leakage-safe public benchmark converter.

    Important:
    - Machine failure is used only as the target label.
    - TWF/HDF/PWF/OSF/RNF are not used as model features.
    - Engineered sensor proxies use only non-target process columns.
    """

    df = raw_df.copy()

    required = [
        "UDI", "Type", "Air temperature [K]", "Process temperature [K]",
        "Rotational speed [rpm]", "Torque [Nm]", "Tool wear [min]",
        "Machine failure"
    ]

    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"AI4I missing required columns: {missing}")

    # Fixed bug: fillna cannot take a NumPy array directly.
    udi = pd.to_numeric(df["UDI"], errors="coerce")
    udi_fallback = pd.Series(np.arange(1, len(df) + 1), index=df.index)
    udi = udi.fillna(udi_fallback).astype(int)

    machine_type = df["Type"].astype(str)

    process_c = pd.to_numeric(df["Process temperature [K]"], errors="coerce") - 273.15
    rpm = pd.to_numeric(df["Rotational speed [rpm]"], errors="coerce")
    torque = pd.to_numeric(df["Torque [Nm]"], errors="coerce")
    wear = pd.to_numeric(df["Tool wear [min]"], errors="coerce")

    torque_delta = (torque - torque.median()).abs()
    rpm_low_signal = (rpm.quantile(0.90) - rpm).clip(lower=0)

    temperature = process_c
    vibration = 2.0 + (torque_delta / 12.0) + (wear / 160.0) + (rpm_low_signal / 900.0)
    current = 35.0 + (torque * 0.75) + (wear / 12.0)
    pressure = 9.5 - (torque_delta / 18.0) - (wear / 260.0)

    alarm_count = (
        (wear > wear.quantile(0.80)).astype(int)
        + (torque > torque.quantile(0.90)).astype(int)
        + (rpm < rpm.quantile(0.10)).astype(int)
        + (process_c > process_c.quantile(0.90)).astype(int)
    )

    criticality_map = {
        "H": ("High", 3),
        "M": ("Medium", 2),
        "L": ("Low", 1),
    }

    criticality = machine_type.map(lambda x: criticality_map.get(x, ("Medium", 2))[0])
    criticality_score = machine_type.map(lambda x: criticality_map.get(x, ("Medium", 2))[1])

    timestamps = pd.date_range(
        start=pd.Timestamp("2025-01-01 00:00:00"),
        periods=len(df),
        freq="min",
    )

    out = pd.DataFrame({
        "source": "public_ai4i_benchmark",
        "timestamp": timestamps.strftime("%Y-%m-%d %H:%M:%S"),
        "asset_id": ["AI4I-" + str(x) for x in udi],
        "asset_type": "Public AI4I Machine",
        "area": "Public Benchmark",
        "criticality": criticality,
        "criticality_score": criticality_score.astype(int),
        "temperature": temperature.round(3),
        "vibration": vibration.round(3),
        "current": current.round(3),
        "pressure": pressure.round(3),
        "rpm": rpm.round(3),
        "alarm_count": alarm_count.astype(int),
        "delay_hours": 0.0,
        "spare_lead_time_days": 0,
        "failure_label": pd.to_numeric(df["Machine failure"], errors="coerce").fillna(0).astype(int),
        "failure_mode": "public_ai4i_target_label_only",
    })

    return out[COMMON_COLUMNS].replace([np.inf, -np.inf], np.nan).dropna(subset=[
        "temperature", "vibration", "current", "pressure", "rpm", "alarm_count", "failure_label"
    ])

try:
    ai4i_raw, ai4i_source_url = download_ai4i_dataset()
    ai4i_raw.to_csv(f"{PUBLIC_DIR}/public_ai4i_raw.csv", index=False)
    ai4i_raw.to_csv(f"{DATA_DIR}/public_ai4i_raw.csv", index=False)

    public_ai4i_df = convert_ai4i_to_common_schema(ai4i_raw)
    PUBLIC_AI4I_AVAILABLE = True
    public_error = ""

except Exception as e:
    ai4i_source_url = ""
    public_ai4i_df = pd.DataFrame(columns=COMMON_COLUMNS)
    PUBLIC_AI4I_AVAILABLE = False
    public_error = str(e)

public_ai4i_df.to_csv(f"{DATA_DIR}/public_ai4i_common_schema.csv", index=False)

steel_df = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs.csv")
if "source" not in steel_df.columns:
    steel_df["source"] = "steel_demo_app"

combined_training_logs = pd.concat(
    [steel_df, public_ai4i_df],
    ignore_index=True,
    sort=False,
)
combined_training_logs.to_csv(f"{DATA_DIR}/combined_training_logs.csv", index=False)

# Compatibility file for older testing/report cells.
steel_compat = steel_df.copy()
steel_compat["source_public"] = 0
steel_compat["is_demo_asset"] = 1

public_compat = public_ai4i_df.copy()
public_compat["source_public"] = 1
public_compat["is_demo_asset"] = 0

sensor_logs_compat = pd.concat(
    [steel_compat, public_compat],
    ignore_index=True,
    sort=False,
)
sensor_logs_compat.to_csv(f"{DATA_DIR}/sensor_logs.csv", index=False)

public_report = {
    "public_ai4i_available": PUBLIC_AI4I_AVAILABLE,
    "source_url": ai4i_source_url,
    "error": public_error,
    "public_rows": int(len(public_ai4i_df)),
    "steel_rows": int(len(steel_df)),
    "combined_rows": int(len(combined_training_logs)),
    "leakage_control": {
        "machine_failure_used_as_feature": False,
        "twf_hdf_pwf_osf_rnf_used_as_features": False,
        "machine_failure_used_only_as_target": True,
        "steel_app_decision_model_separate_from_public_benchmark": True,
    },
}

with open(f"{DATA_DIR}/public_ai4i_report.json", "w", encoding="utf-8") as f:
    json.dump(public_report, f, indent=2)

with open(f"{BASE_DIR}/DATA_SOURCES.md", "w", encoding="utf-8") as f:
    f.write("""# Data Sources

## Steel demo data
Synthetic steel maintenance data is generated for four industrial assets:
MTR-204, GBX-17, PMP-09, and HPP-12.

It includes sensor logs, maintenance history, failure reports, delay logs,
incident records, spare inventory, feedback logs, and a digital logbook.

## Public AI4I benchmark
The AI4I 2020 Predictive Maintenance dataset is used only as an external
public benchmark to demonstrate ML validation.

Leakage control:
- `Machine failure` is used only as the supervised target label.
- Failure subtype labels such as TWF, HDF, PWF, OSF, and RNF are not used as model features.
- Sensor proxy fields are engineered only from non-target process variables.
- The steel app decision layer uses a separate steel demo model plus operational rules.
""")

print("Cell 3B complete")
print("Public AI4I available:", PUBLIC_AI4I_AVAILABLE)
print("Public AI4I rows:", len(public_ai4i_df))
print("Steel rows:", len(steel_df))
print("Combined rows:", len(combined_training_logs))
print("Compatibility sensor_logs.csv rows:", len(sensor_logs_compat))
print("Leakage removed: Machine failure is target only, not a feature")
if public_error:
    print("Public dataset note:", public_error)

Cell 3B complete
Public AI4I available: True
Public AI4I rows: 10000
Steel rows: 2880
Combined rows: 12880
Compatibility sensor_logs.csv rows: 12880
Leakage removed: Machine failure is target only, not a feature

In [5]:
# ============================================================
# Cell 4: Separate public benchmark model + steel hybrid app risk
# Fixed:
# - Creates failure_in_7d safely
# - No old sensor_logs/source_public dependency
# - Handles mixed timestamps
# - Keeps AI4I benchmark separate from steel app decisions
# ============================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, roc_auc_score, precision_recall_curve

Path(REPORT_DIR).mkdir(parents=True, exist_ok=True)

feature_cols = ["temperature", "vibration", "current", "pressure", "rpm", "alarm_count"]

def safe_float(x, default=0.0):
    try:
        if pd.isna(x):
            return default
        return float(x)
    except Exception:
        return default

def risk_band_from_score(score):
    score = safe_float(score)
    if score >= 75:
        return "CRITICAL"
    if score >= 55:
        return "HIGH"
    if score >= 35:
        return "MEDIUM"
    return "LOW"

def add_sequence_split(df, split_mode="asset"):
    df = df.copy()

    df["timestamp"] = pd.to_datetime(df["timestamp"], format="mixed", errors="coerce")
    df = df.dropna(subset=["timestamp"]).copy()

    for col in feature_cols + ["failure_label"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna(subset=feature_cols + ["failure_label"]).copy()
    df["failure_label"] = df["failure_label"].astype(int)

    if split_mode == "global":
        df = df.sort_values("timestamp").reset_index(drop=True)
        df["seq_id"] = np.arange(len(df))
        df["seq_count"] = len(df)
        df["seq_pct"] = df["seq_id"] / max(len(df) - 1, 1)
    else:
        df = df.sort_values(["asset_id", "timestamp"]).reset_index(drop=True)
        df["seq_id"] = df.groupby("asset_id").cumcount()
        df["seq_count"] = df.groupby("asset_id")["seq_id"].transform("max") + 1
        df["seq_pct"] = df["seq_id"] / df["seq_count"].clip(lower=1)

    return df

def add_failure_target(df, target_mode="future_7d", horizon_steps=168):
    df = df.copy()

    if target_mode == "direct":
        df["failure_in_7d"] = df["failure_label"].astype(int)
        return df

    targets = []

    for _, g in df.groupby("asset_id", sort=False):
        y = g["failure_label"].astype(int)
        future_target = (
            y.iloc[::-1]
            .rolling(window=horizon_steps + 1, min_periods=1)
            .max()
            .iloc[::-1]
            .astype(int)
        )
        targets.append(future_target)

    df["failure_in_7d"] = pd.concat(targets).sort_index().astype(int)
    return df

def tune_threshold(y_true, proba, target_recall=0.75):
    y_true = pd.Series(y_true).astype(int)

    if y_true.nunique() < 2:
        return 0.5

    precision, recall, thresholds = precision_recall_curve(y_true, proba)

    if len(thresholds) == 0:
        return 0.5

    valid = np.where(recall[:-1] >= target_recall)[0]

    if len(valid) > 0:
        best_idx = valid[np.argmax(precision[valid])]
        return float(thresholds[best_idx])

    f1 = (2 * precision[:-1] * recall[:-1]) / np.maximum(precision[:-1] + recall[:-1], 1e-9)
    return float(thresholds[int(np.argmax(f1))])

def train_model_block(df, label, target_mode="future_7d", split_mode="asset"):
    df = add_sequence_split(df, split_mode=split_mode)
    df = add_failure_target(df, target_mode=target_mode)

    X = df[feature_cols].copy()
    y = df["failure_in_7d"].astype(int)

    train_mask = df["seq_pct"] <= 0.70
    val_mask = (df["seq_pct"] > 0.70) & (df["seq_pct"] <= 0.85)
    test_mask = df["seq_pct"] > 0.85

    if y.loc[train_mask].nunique() < 2:
        print(f"\nWarning: {label} train split has one class only. Using full data fallback split.")
        train_mask = df["seq_pct"] <= 0.80
        val_mask = (df["seq_pct"] > 0.80) & (df["seq_pct"] <= 0.90)
        test_mask = df["seq_pct"] > 0.90

    risk_model = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("model", RandomForestClassifier(
            n_estimators=350,
            max_depth=7,
            min_samples_leaf=6,
            class_weight="balanced_subsample",
            random_state=42,
            n_jobs=-1,
        )),
    ])

    anomaly_model = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("model", IsolationForest(
            n_estimators=250,
            contamination=0.08,
            random_state=42,
        )),
    ])

    risk_model.fit(X.loc[train_mask], y.loc[train_mask])
    anomaly_model.fit(X.loc[train_mask])

    if val_mask.sum() > 0:
        val_proba = risk_model.predict_proba(X.loc[val_mask])[:, 1]
        best_threshold = tune_threshold(y.loc[val_mask], val_proba, target_recall=0.75)
    else:
        best_threshold = 0.5

    metrics = {
        "label": label,
        "target_mode": target_mode,
        "split_mode": split_mode,
        "best_threshold": float(best_threshold),
        "train_rows": int(train_mask.sum()),
        "validation_rows": int(val_mask.sum()),
        "test_rows": int(test_mask.sum()),
        "positive_rate": float(y.mean()),
    }

    for split_name, mask in [("validation", val_mask), ("test", test_mask)]:
        if mask.sum() > 0 and y.loc[mask].nunique() > 1:
            proba = risk_model.predict_proba(X.loc[mask])[:, 1]
            pred = (proba >= best_threshold).astype(int)
            auc = roc_auc_score(y.loc[mask], proba)

            print(f"\n{label.upper()} {split_name.upper()}")
            print("Threshold:", round(best_threshold, 4))
            print(classification_report(y.loc[mask], pred))
            print("ROC AUC:", round(auc, 4))

            metrics[f"{split_name}_roc_auc"] = float(auc)
        else:
            metrics[f"{split_name}_roc_auc"] = None

    return df, risk_model, anomaly_model, best_threshold, metrics

def slope_values(s, window=24):
    out = []
    vals = s.astype(float)

    for i in range(len(vals)):
        x = vals.iloc[max(0, i - window + 1): i + 1].dropna().values

        if len(x) < 4:
            out.append(0.0)
        else:
            out.append(float(np.polyfit(np.arange(len(x)), x, 1)[0]))

    return pd.Series(out, index=s.index)

# ------------------------------------------------------------
# Load clean sources from Cell 3 and Cell 3B
# ------------------------------------------------------------

steel_df = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs.csv")

public_path = f"{DATA_DIR}/public_ai4i_common_schema.csv"
if os.path.exists(public_path):
    public_df = pd.read_csv(public_path)
else:
    public_df = pd.DataFrame()

# ------------------------------------------------------------
# Public benchmark model: direct public target only
# ------------------------------------------------------------

if not public_df.empty and public_df["failure_label"].nunique() > 1:
    public_df, public_risk_model, public_anomaly_model, PUBLIC_THRESHOLD, public_metrics = train_model_block(
        public_df,
        "public_ai4i_benchmark",
        target_mode="direct",
        split_mode="global",
    )
else:
    public_risk_model = None
    public_anomaly_model = None
    PUBLIC_THRESHOLD = 0.5
    public_metrics = {
        "label": "public_ai4i_benchmark",
        "available": False,
        "reason": "public_ai4i_common_schema.csv missing or one-class target",
    }

# ------------------------------------------------------------
# Steel app model: future 7-day target
# ------------------------------------------------------------

steel_df, steel_risk_model, steel_anomaly_model, STEEL_THRESHOLD, steel_metrics = train_model_block(
    steel_df,
    "steel_demo_app",
    target_mode="future_7d",
    split_mode="asset",
)

X_steel = steel_df[feature_cols].copy()

steel_df["ml_failure_risk"] = steel_risk_model.predict_proba(X_steel)[:, 1]
steel_df["ml_failure_pred"] = (steel_df["ml_failure_risk"] >= STEEL_THRESHOLD).astype(int)

steel_df["anomaly_score"] = -steel_anomaly_model.decision_function(X_steel)
steel_df["is_anomaly"] = (steel_anomaly_model.predict(X_steel) == -1).astype(int)

for col in ["temperature", "vibration", "pressure", "current"]:
    steel_df[f"{col}_slope_24h"] = 0.0

    for asset_id, idx in steel_df.groupby("asset_id").groups.items():
        steel_df.loc[idx, f"{col}_slope_24h"] = slope_values(steel_df.loc[idx, col]).values

steel_df["anomaly_events_24h"] = (
    steel_df.groupby("asset_id")["is_anomaly"]
    .rolling(24, min_periods=1)
    .sum()
    .reset_index(level=0, drop=True)
)

delay_logs_df = pd.read_csv(f"{DATA_DIR}/delay_logs.csv")
delay_map = delay_logs_df.set_index("asset_id")["delay_hours"].to_dict()

def operational_rule_score(row):
    typ = str(row.get("asset_type", "")).lower()
    criticality = str(row.get("criticality", "medium")).lower()

    temp = safe_float(row.get("temperature"))
    vib = safe_float(row.get("vibration"))
    current = safe_float(row.get("current"))
    pressure = safe_float(row.get("pressure"), 8)
    alarms = safe_float(row.get("alarm_count"))
    anomalies = safe_float(row.get("anomaly_events_24h"))
    delay = safe_float(delay_map.get(row.get("asset_id"), 0))

    score = 0.0

    if "gearbox" in typ:
        if vib >= 7:
            score += 30
        if vib >= 9:
            score += 20
        if vib >= 10:
            score += 10
        if temp >= 65:
            score += 8

    if "motor" in typ:
        if temp >= 80:
            score += 25
        if temp >= 85:
            score += 15
        if current >= 80:
            score += 12
        if vib >= 5:
            score += 8

    if "pump" in typ:
        if pressure <= 6:
            score += 22
        if vib >= 5:
            score += 12
        if current >= 75:
            score += 8

    if "hydraulic" in typ:
        if pressure <= 6:
            score += 25
        if temp >= 65:
            score += 10
        if alarms >= 2:
            score += 8

    if alarms >= 2:
        score += 8
    if alarms >= 4:
        score += 8

    if anomalies >= 6:
        score += 15
    if anomalies >= 18:
        score += 10

    score += {"critical": 15, "high": 10, "medium": 5, "low": 0}.get(criticality, 5)
    score += min(delay * 2.0, 12)

    return round(float(np.clip(score, 0, 100)), 2)

steel_df["operational_rule_score"] = steel_df.apply(operational_rule_score, axis=1)

steel_df["hybrid_health_score"] = (
    0.45 * (steel_df["ml_failure_risk"] * 100)
    + 0.55 * steel_df["operational_rule_score"]
).clip(0, 100)

steel_df["hybrid_failure_risk"] = (steel_df["hybrid_health_score"] / 100).round(4)
steel_df["failure_risk"] = steel_df["hybrid_failure_risk"]
steel_df["failure_pred"] = (steel_df["hybrid_health_score"] >= 55).astype(int)
steel_df["risk_band"] = steel_df["hybrid_health_score"].apply(risk_band_from_score)

def estimate_rul(row):
    risk = safe_float(row["hybrid_failure_risk"])
    anomaly_events = safe_float(row["anomaly_events_24h"])
    criticality = str(row["criticality"]).lower()

    rul = 50 * (1 - risk)
    rul -= anomaly_events * 0.45
    rul -= max(0, safe_float(row["temperature_slope_24h"])) * 4.0
    rul -= max(0, safe_float(row["vibration_slope_24h"])) * 8.0
    rul -= max(0, -safe_float(row["pressure_slope_24h"])) * 5.0
    rul -= {"critical": 5, "high": 3, "medium": 1, "low": 0}.get(criticality, 1)

    return round(float(np.clip(rul, 1.0, 60.0)), 1)

steel_df["estimated_rul_days"] = steel_df.apply(estimate_rul, axis=1)

# ------------------------------------------------------------
# Save scored data for later cells
# ------------------------------------------------------------

steel_df.to_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv", index=False)
steel_df.to_csv(f"{DATA_DIR}/sensor_logs_scored.csv", index=False)

if not public_df.empty:
    public_df.to_csv(f"{DATA_DIR}/public_ai4i_scored.csv", index=False)

asset_health = (
    steel_df.sort_values("timestamp")
    .groupby("asset_id")
    .tail(1)
    .sort_values(["hybrid_health_score", "estimated_rul_days"], ascending=[False, True])
)

asset_health.to_csv(f"{DATA_DIR}/asset_health_summary.csv", index=False)

model_summary = {
    "public_model": public_metrics,
    "steel_demo_model": steel_metrics,
    "important_note": "AI4I is a leakage-free public benchmark. Steel app decisions use a separate steel model plus operational rules.",
    "steel_threshold": float(STEEL_THRESHOLD),
    "public_threshold": float(PUBLIC_THRESHOLD),
    "hybrid_formula": "0.45 * ML failure risk + 0.55 * operational rule score",
    "target_definitions": {
        "public_ai4i_benchmark": "direct Machine failure target, not used as feature",
        "steel_demo_app": "failure_in_7d created from future failure_label within each asset sequence",
    },
}

Path(f"{REPORT_DIR}/model_summary.json").write_text(json.dumps(model_summary, indent=2), encoding="utf-8")

print("\nModel summary:")
print(json.dumps(model_summary, indent=2))

print("\nDemo asset health summary:")
display(asset_health[[
    "asset_id", "asset_type", "area", "criticality",
    "temperature", "vibration", "pressure", "alarm_count",
    "ml_failure_risk", "operational_rule_score", "hybrid_health_score",
    "failure_risk", "failure_pred", "risk_band", "estimated_rul_days",
    "anomaly_events_24h"
]])

PUBLIC_AI4I_BENCHMARK VALIDATION
Threshold: 0.5459
              precision    recall  f1-score   support

           0       0.99      0.88      0.93      1468
           1       0.13      0.78      0.22        32

    accuracy                           0.88      1500
   macro avg       0.56      0.83      0.58      1500
weighted avg       0.98      0.88      0.92      1500

ROC AUC: 0.9313

PUBLIC_AI4I_BENCHMARK TEST
Threshold: 0.5459
              precision    recall  f1-score   support

           0       0.99      0.96      0.98      1471
           1       0.24      0.69      0.36        29

    accuracy                           0.95      1500
   macro avg       0.62      0.82      0.67      1500
weighted avg       0.98      0.95      0.96      1500

ROC AUC: 0.944

STEEL_DEMO_APP VALIDATION
Threshold: 0.0438
              precision    recall  f1-score   support

           0       0.43      1.00      0.60        12
           1       1.00      0.96      0.98       420

    accuracy                           0.96       432
   macro avg       0.71      0.98      0.79       432
weighted avg       0.98      0.96      0.97       432

ROC AUC: 0.9887

Model summary:
{
  "public_model": {
    "label": "public_ai4i_benchmark",
    "target_mode": "direct",
    "split_mode": "global",
    "best_threshold": 0.545928313124836,
    "train_rows": 7000,
    "validation_rows": 1500,
    "test_rows": 1500,
    "positive_rate": 0.0339,
    "validation_roc_auc": 0.931262772479564,
    "test_roc_auc": 0.9440211913078131
  },
  "steel_demo_model": {
    "label": "steel_demo_app",
    "target_mode": "future_7d",
    "split_mode": "asset",
    "best_threshold": 0.04382305057411851,
    "train_rows": 2020,
    "validation_rows": 432,
    "test_rows": 428,
    "positive_rate": 0.32395833333333335,
    "validation_roc_auc": 0.9886904761904762,
    "test_roc_auc": null
  },
  "important_note": "AI4I is a leakage-free public benchmark. Steel app decisions use a separate steel model plus operational rules.",
  "steel_threshold": 0.04382305057411851,
  "public_threshold": 0.545928313124836,
  "hybrid_formula": "0.45 * ML failure risk + 0.55 * operational rule score",
  "target_definitions": {
    "public_ai4i_benchmark": "direct Machine failure target, not used as feature",
    "steel_demo_app": "failure_in_7d created from future failure_label within each asset sequence"
  }
}

Demo asset health summary:

,asset_id,asset_type,area,criticality,temperature,vibration,pressure,alarm_count,ml_failure_risk,operational_rule_score,hybrid_health_score,failure_risk,failure_pred,risk_band,estimated_rul_days,anomaly_events_24h
719,GBX-17,Gearbox,Finishing Mill,Critical,71.758,11.000,9.798,3,0.603967,100.0,82.178498,0.8218,1,CRITICAL,1.0,24.0
2159,MTR-204,Induction Motor,Hot Strip Mill,High,91.988,5.693,9.056,3,0.506254,100.0,77.781417,0.7778,1,CRITICAL,1.0,24.0
1439,HPP-12,Hydraulic Power Pack,Plate Mill,Medium,66.402,4.068,4.811,3,0.535986,89.0,73.069350,0.7307,1,HIGH,1.3,24.0
2879,PMP-09,Cooling Water Pump,Caster Utility,High,60.517,6.586,4.141,3,0.541421,87.0,72.213927,0.7221,1,HIGH,1.0,24.0

In [6]:
# ============================================================
# Cell 5: Robust metadata-filtered RAG index
# Fixed:
# - Filename-first SOP metadata classification
# - No more hydraulic SOP becoming pump
# - No more pump SOP becoming gearbox
# - Handles timestamp/date and action/action_taken schema differences
# ============================================================

from pathlib import Path
import numpy as np
import pandas as pd

def row_get(row, names, default="Not available"):
    for name in names:
        if name in row.index and pd.notna(row[name]):
            return row[name]
    return default

def normalize_equipment_type(value):
    text = str(value).lower()

    if "motor" in text:
        return "motor"
    if "gearbox" in text or "gear" in text:
        return "gearbox"
    if "pump" in text:
        return "pump"
    if "hydraulic" in text or "hpp" in text:
        return "hydraulic"
    if "public" in text or "ai4i" in text:
        return "public_dataset"
    if "policy" in text:
        return "policy"

    return text.replace(" ", "_").strip() or "general"

def infer_doc_metadata(filename, text):
    """
    Filename-first metadata. This prevents generic body words like
    'pump inspection' or 'temperature' from corrupting SOP labels.
    """

    name = str(filename).lower()

    filename_map = {
        "sop_mtr_204": ("motor", "overheating"),
        "sop_gbx_17": ("gearbox", "vibration"),
        "sop_pmp_09": ("pump", "cavitation"),
        "sop_hpp_12": ("hydraulic", "pressure"),
        "maintenance_prioritization": ("policy", "priority"),
        "feedback_learning": ("policy", "feedback"),
        "data_sources": ("public_dataset", "data source"),
    }

    for key, value in filename_map.items():
        if key in name:
            return value

    text_l = str(text).lower()

    for line in str(text).splitlines():
        line_clean = line.strip().lower()

        if line_clean.startswith("equipment type:"):
            equipment_type = normalize_equipment_type(
                line_clean.replace("equipment type:", "").strip()
            )
            issue_type = "general"

            if "issue type:" in text_l:
                for line2 in str(text).splitlines():
                    line2_clean = line2.strip().lower()
                    if line2_clean.startswith("issue type:"):
                        issue_type = line2_clean.replace("issue type:", "").strip()
                        break

            return equipment_type, issue_type

    if "asset mtr" in text_l or "induction motor" in text_l:
        return "motor", "overheating"
    if "asset gbx" in text_l or "gbx-17" in text_l or "gearbox" in text_l:
        return "gearbox", "vibration"
    if "asset pmp" in text_l or "pmp-09" in text_l or "cooling water pump" in text_l:
        return "pump", "cavitation"
    if "asset hpp" in text_l or "hpp-12" in text_l or "hydraulic power pack" in text_l:
        return "hydraulic", "pressure"
    if "priority" in text_l or "prioritize" in text_l:
        return "policy", "priority"
    if "feedback" in text_l:
        return "policy", "feedback"
    if "ai4i" in text_l or "public benchmark" in text_l:
        return "public_dataset", "data source"

    return "general", "general"

def chunk_text(text, chunk_size=120, overlap=25):
    words = str(text).split()
    chunks = []
    start = 0

    while start < len(words):
        end = min(start + chunk_size, len(words))
        chunk = " ".join(words[start:end]).strip()
        if chunk:
            chunks.append(chunk)
        start += max(chunk_size - overlap, 1)

    return chunks or [str(text).strip()]

doc_records = []

# ------------------------------------------------------------
# SOP/manual/policy documents
# ------------------------------------------------------------

for path in Path(DOC_DIR).glob("*.txt"):
    text = path.read_text(encoding="utf-8")
    equipment_type, issue_type = infer_doc_metadata(path.name, text)

    for i, chunk in enumerate(chunk_text(text)):
        doc_records.append({
            "source": path.name,
            "chunk_id": int(i),
            "asset_id": "ALL",
            "equipment_type": equipment_type,
            "issue_type": issue_type,
            "text": chunk,
        })

# ------------------------------------------------------------
# Structured operational files
# ------------------------------------------------------------

history_df = pd.read_csv(f"{DATA_DIR}/maintenance_history.csv")
failure_reports_df = pd.read_csv(f"{DATA_DIR}/failure_reports.csv")
spares_df = pd.read_csv(f"{DATA_DIR}/spares_inventory.csv")
delay_logs_df = pd.read_csv(f"{DATA_DIR}/delay_logs.csv")

incident_path = f"{DATA_DIR}/incident_records.csv"
incident_df = pd.read_csv(incident_path) if Path(incident_path).exists() else pd.DataFrame()

asset_health_path = f"{DATA_DIR}/asset_health_summary.csv"
if Path(asset_health_path).exists():
    asset_map_df = pd.read_csv(asset_health_path)
else:
    asset_map_df = pd.read_csv(f"{DATA_DIR}/asset_master.csv")

asset_type_map = asset_map_df.set_index("asset_id")["asset_type"].to_dict()

def asset_equipment(asset_id):
    return normalize_equipment_type(asset_type_map.get(asset_id, "unknown"))

for idx, row in history_df.iterrows():
    asset_id = row_get(row, ["asset_id"])
    date_value = row_get(row, ["timestamp", "date"])
    issue = row_get(row, ["issue", "failure_mode", "problem"])
    action = row_get(row, ["action_taken", "action", "corrective_action"])
    result = row_get(row, ["result", "outcome"])
    downtime = row_get(row, ["downtime_hours"], 0)

    doc_records.append({
        "source": "maintenance_history.csv",
        "chunk_id": int(idx),
        "asset_id": asset_id,
        "equipment_type": asset_equipment(asset_id),
        "issue_type": "history",
        "text": (
            f"Historical maintenance record for {asset_id}. "
            f"Date: {date_value}. Issue: {issue}. "
            f"Action: {action}. Result: {result}. Downtime hours: {downtime}."
        ),
    })

for idx, row in failure_reports_df.iterrows():
    asset_id = row_get(row, ["asset_id"])
    date_value = row_get(row, ["timestamp", "date"])
    failure_mode = row_get(row, ["failure_mode", "issue"])
    root_cause = row_get(row, ["root_cause", "cause"])
    corrective_action = row_get(row, ["corrective_action", "action_taken", "action"])
    business_impact = row_get(row, ["business_impact", "impact"])

    doc_records.append({
        "source": "failure_reports.csv",
        "chunk_id": int(idx),
        "asset_id": asset_id,
        "equipment_type": asset_equipment(asset_id),
        "issue_type": "failure report",
        "text": (
            f"Failure report for {asset_id}. Date: {date_value}. "
            f"Failure mode: {failure_mode}. Root cause: {root_cause}. "
            f"Corrective action: {corrective_action}. Business impact: {business_impact}."
        ),
    })

for idx, row in spares_df.iterrows():
    asset_id = row_get(row, ["asset_id"])
    spare = row_get(row, ["spare_part", "part_name"])
    stock = row_get(row, ["stock_qty", "quantity"])
    lead_time = row_get(row, ["lead_time_days", "procurement_lead_time_days"])
    criticality = row_get(row, ["spare_criticality", "criticality"])
    cost = row_get(row, ["unit_cost_inr", "cost"], "Not available")

    doc_records.append({
        "source": "spares_inventory.csv",
        "chunk_id": int(idx),
        "asset_id": asset_id,
        "equipment_type": asset_equipment(asset_id),
        "issue_type": "spares",
        "text": (
            f"Spare inventory for {asset_id}. Part: {spare}. "
            f"Stock quantity: {stock}. Procurement lead time days: {lead_time}. "
            f"Spare criticality: {criticality}. Unit cost INR: {cost}."
        ),
    })

for idx, row in delay_logs_df.iterrows():
    asset_id = row_get(row, ["asset_id"])
    area = row_get(row, ["area"])
    delay_hours = row_get(row, ["delay_hours"], 0)
    reason = row_get(row, ["delay_reason", "production_impact", "impact"])

    doc_records.append({
        "source": "delay_logs.csv",
        "chunk_id": int(idx),
        "asset_id": asset_id,
        "equipment_type": asset_equipment(asset_id),
        "issue_type": "delay",
        "text": (
            f"Delay log for {asset_id}. Area: {area}. "
            f"Delay hours: {delay_hours}. Production impact or delay reason: {reason}."
        ),
    })

for idx, row in incident_df.iterrows():
    asset_id = row_get(row, ["asset_id"])
    incident = row_get(row, ["incident_summary", "summary", "incident"])
    severity = row_get(row, ["severity"])
    response = row_get(row, ["recommended_response", "response", "action"])

    doc_records.append({
        "source": "incident_records.csv",
        "chunk_id": int(idx),
        "asset_id": asset_id,
        "equipment_type": asset_equipment(asset_id),
        "issue_type": "incident",
        "text": (
            f"Incident record for {asset_id}. Severity: {severity}. "
            f"Incident: {incident}. Recommended response: {response}."
        ),
    })

# ------------------------------------------------------------
# Latest scored asset health records
# ------------------------------------------------------------

if Path(asset_health_path).exists():
    asset_health_df = pd.read_csv(asset_health_path)

    for idx, row in asset_health_df.iterrows():
        asset_id = row_get(row, ["asset_id"])

        doc_records.append({
            "source": "asset_health_summary.csv",
            "chunk_id": int(idx),
            "asset_id": asset_id,
            "equipment_type": asset_equipment(asset_id),
            "issue_type": "current health",
            "text": (
                f"Latest asset health for {asset_id}. "
                f"Risk band: {row_get(row, ['risk_band'])}. "
                f"Hybrid failure risk: {row_get(row, ['failure_risk', 'hybrid_failure_risk'])}. "
                f"ML failure risk: {row_get(row, ['ml_failure_risk'])}. "
                f"Operational rule score: {row_get(row, ['operational_rule_score'])}. "
                f"Hybrid health score: {row_get(row, ['hybrid_health_score'])}. "
                f"Estimated RUL days: {row_get(row, ['estimated_rul_days'])}. "
                f"Temperature: {row_get(row, ['temperature'])}. "
                f"Vibration: {row_get(row, ['vibration'])}. "
                f"Pressure: {row_get(row, ['pressure'])}. "
                f"Alarm count: {row_get(row, ['alarm_count'])}."
            ),
        })

# ------------------------------------------------------------
# Data source documentation
# ------------------------------------------------------------

data_sources_path = Path(f"{BASE_DIR}/DATA_SOURCES.md")
if data_sources_path.exists():
    data_source_text = data_sources_path.read_text(encoding="utf-8")
    equipment_type, issue_type = infer_doc_metadata("DATA_SOURCES.md", data_source_text)

    doc_records.append({
        "source": "DATA_SOURCES.md",
        "chunk_id": 0,
        "asset_id": "ALL",
        "equipment_type": equipment_type,
        "issue_type": issue_type,
        "text": data_source_text,
    })

doc_df = pd.DataFrame(doc_records).dropna(subset=["text"]).reset_index(drop=True)
doc_df["text"] = doc_df["text"].astype(str)
doc_df.to_csv(f"{DATA_DIR}/rag_documents.csv", index=False)

print("RAG documents:", doc_df.shape)
display(doc_df[["source", "asset_id", "equipment_type", "issue_type"]].drop_duplicates().head(30))

# ------------------------------------------------------------
# Embedding backend with fallback
# ------------------------------------------------------------

RAG_BACKEND = "sentence_transformer"

try:
    EMBED_MODEL_ID = "BAAI/bge-small-en-v1.5"
    embedder = SentenceTransformer(EMBED_MODEL_ID, device="cpu")

    embeddings = embedder.encode(
        doc_df["text"].tolist(),
        normalize_embeddings=True,
        show_progress_bar=True,
        batch_size=16,
        device="cpu",
    )
    embeddings = np.array(embeddings).astype("float32")

except Exception as e:
    print("SentenceTransformer failed, falling back to TF-IDF:", str(e))

    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.preprocessing import normalize

    RAG_BACKEND = "tfidf"
    embedder = TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 2),
        max_features=6000,
    )
    embeddings = embedder.fit_transform(doc_df["text"].tolist())
    embeddings = normalize(embeddings)

asset_source_path = f"{DATA_DIR}/asset_health_summary.csv"
if Path(asset_source_path).exists():
    ASSET_IDS_RAG = sorted(pd.read_csv(asset_source_path)["asset_id"].unique().tolist())
else:
    ASSET_IDS_RAG = sorted(pd.read_csv(f"{DATA_DIR}/asset_master.csv")["asset_id"].unique().tolist())

def query_assets(query):
    q = str(query).upper()
    return [a for a in ASSET_IDS_RAG if a.upper() in q]

def query_equipment_type(query):
    q = str(query).lower()

    if any(w in q for w in ["mtr-204", "motor", "overheat", "overheating", "current"]):
        return "motor"
    if any(w in q for w in ["gbx-17", "gearbox", "gear", "vibration", "bearing"]):
        return "gearbox"
    if any(w in q for w in ["pmp-09", "pump", "cavitation", "suction"]):
        return "pump"
    if any(w in q for w in ["hpp-12", "hydraulic", "pressure", "filter", "relief"]):
        return "hydraulic"
    if any(w in q for w in ["public", "dataset", "ai4i", "uci", "source"]):
        return "public_dataset"

    return None

def encode_query(query):
    if RAG_BACKEND == "sentence_transformer":
        q_emb = embedder.encode([query], normalize_embeddings=True, device="cpu")
        return np.array(q_emb).astype("float32")[0]

    q_vec = embedder.transform([query])
    return q_vec

def retrieve_docs(query, top_k=5, asset_id=None, equipment_type=None, plant_level=False):
    asset_ids = [asset_id] if asset_id else query_assets(query)
    equipment_type = normalize_equipment_type(equipment_type) if equipment_type else query_equipment_type(query)

    candidates = doc_df.copy()

    if not plant_level:
        mask = candidates["equipment_type"].isin(["policy", "public_dataset"])

        if asset_ids:
            mask = mask | candidates["asset_id"].isin(asset_ids)

        if equipment_type:
            mask = mask | candidates["equipment_type"].eq(equipment_type)

        candidates = candidates[mask].copy()

    if candidates.empty:
        candidates = doc_df.copy()

    cand_idx = candidates.index.values

    if RAG_BACKEND == "sentence_transformer":
        q_emb = encode_query(query)
        scores = embeddings[cand_idx] @ q_emb
    else:
        q_vec = encode_query(query)
        scores = (embeddings[cand_idx] @ q_vec.T).toarray().ravel()

    order = np.argsort(scores)[::-1][:min(top_k, len(scores))]

    results = []
    for pos in order:
        idx = int(cand_idx[pos])
        row = doc_df.loc[idx]

        results.append({
            "score": float(scores[pos]),
            "source": row["source"],
            "asset_id": row["asset_id"],
            "equipment_type": row["equipment_type"],
            "issue_type": row["issue_type"],
            "text": row["text"],
        })

    return results

print("\nRAG backend:", RAG_BACKEND)

print("\nMetadata check:")
metadata_check = doc_df[["source", "equipment_type", "issue_type"]].drop_duplicates().sort_values("source")
display(metadata_check)

print("\nExpected SOP labels:")
expected_sources = [
    "SOP_MTR_204_motor_overheating.txt",
    "SOP_GBX_17_gearbox_vibration.txt",
    "SOP_PMP_09_cavitation.txt",
    "SOP_HPP_12_hydraulic_pressure.txt",
    "maintenance_prioritization_policy.txt",
    "feedback_learning_policy.txt",
    "DATA_SOURCES.md",
]
display(metadata_check[metadata_check["source"].isin(expected_sources)])

print("\nMotor retrieval check:")
for item in retrieve_docs("MTR-204 motor overheating bearing lubrication", top_k=4, asset_id="MTR-204"):
    print("-", item["source"], "|", item["asset_id"], "|", item["equipment_type"], "|", item["issue_type"], "|", item["text"][:180])

RAG documents: (35, 6)

,source,asset_id,equipment_type,issue_type
0,SOP_MTR_204_motor_overheating.txt,ALL,motor,overheating
1,SOP_GBX_17_gearbox_vibration.txt,ALL,gearbox,vibration
2,maintenance_prioritization_policy.txt,ALL,policy,priority
3,SOP_PMP_09_cavitation.txt,ALL,pump,cavitation
4,feedback_learning_policy.txt,ALL,policy,feedback
5,SOP_HPP_12_hydraulic_pressure.txt,ALL,hydraulic,pressure
6,maintenance_history.csv,MTR-204,motor,history
7,maintenance_history.csv,GBX-17,gearbox,history
8,maintenance_history.csv,PMP-09,pump,history
9,maintenance_history.csv,HPP-12,hydraulic,history
10,failure_reports.csv,MTR-204,motor,failure report
11,failure_reports.csv,GBX-17,gearbox,failure report
12,failure_reports.csv,PMP-09,pump,failure report
13,failure_reports.csv,HPP-12,hydraulic,failure report
14,spares_inventory.csv,MTR-204,motor,spares
16,spares_inventory.csv,GBX-17,gearbox,spares
18,spares_inventory.csv,PMP-09,pump,spares
20,spares_inventory.csv,HPP-12,hydraulic,spares
22,delay_logs.csv,MTR-204,motor,delay
23,delay_logs.csv,GBX-17,gearbox,delay
24,delay_logs.csv,PMP-09,pump,delay
25,delay_logs.csv,HPP-12,hydraulic,delay
26,incident_records.csv,MTR-204,motor,incident
27,incident_records.csv,GBX-17,gearbox,incident
28,incident_records.csv,PMP-09,pump,incident
29,incident_records.csv,HPP-12,hydraulic,incident
30,asset_health_summary.csv,GBX-17,gearbox,current health
31,asset_health_summary.csv,MTR-204,motor,current health
32,asset_health_summary.csv,HPP-12,hydraulic,current health
33,asset_health_summary.csv,PMP-09,pump,current health

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/3 [00:00<?, ?it/s]

RAG backend: sentence_transformer

Metadata check:

                                   source  equipment_type      issue_type
34                        DATA_SOURCES.md  public_dataset     data source
1        SOP_GBX_17_gearbox_vibration.txt         gearbox       vibration
5       SOP_HPP_12_hydraulic_pressure.txt       hydraulic        pressure
0       SOP_MTR_204_motor_overheating.txt           motor     overheating
3               SOP_PMP_09_cavitation.txt            pump      cavitation
33               asset_health_summary.csv            pump  current health
31               asset_health_summary.csv           motor  current health
32               asset_health_summary.csv       hydraulic  current health
30               asset_health_summary.csv         gearbox  current health
22                         delay_logs.csv           motor           delay
23                         delay_logs.csv         gearbox           delay
24                         delay_logs.csv            pump           delay
25                         delay_logs.csv       hydraulic           delay
10                    failure_reports.csv           motor  failure report
11                    failure_reports.csv         gearbox  failure report
12                    failure_reports.csv            pump  failure report
13                    failure_reports.csv       hydraulic  failure report
4            feedback_learning_policy.txt          policy        feedback
28                   incident_records.csv            pump        incident
29                   incident_records.csv       hydraulic        incident
27                   incident_records.csv         gearbox        incident
26                   incident_records.csv           motor        incident
9                 maintenance_history.csv       hydraulic         history
6                 maintenance_history.csv           motor         history
7                 maintenance_history.csv         gearbox         history
8                 maintenance_history.csv            pump         history
2   maintenance_prioritization_policy.txt          policy        priority
20                   spares_inventory.csv       hydraulic          spares
14                   spares_inventory.csv           motor          spares
18                   spares_inventory.csv            pump          spares
16                   spares_inventory.csv         gearbox          spares

Expected SOP labels:

                                   source  equipment_type   issue_type
34                        DATA_SOURCES.md  public_dataset  data source
1        SOP_GBX_17_gearbox_vibration.txt         gearbox    vibration
5       SOP_HPP_12_hydraulic_pressure.txt       hydraulic     pressure
0       SOP_MTR_204_motor_overheating.txt           motor  overheating
3               SOP_PMP_09_cavitation.txt            pump   cavitation
4            feedback_learning_policy.txt          policy     feedback
2   maintenance_prioritization_policy.txt          policy     priority

Motor retrieval check:
- failure_reports.csv | MTR-204 | motor | failure report | Failure report for MTR-204. Date: 2026-04-18 07:45:00. Failure mode: Overheating. Root cause: Bearing lubrication degradation. Corrective action: Regrease bearing, inspect load cur
- SOP_MTR_204_motor_overheating.txt | ALL | motor | overheating | Asset MTR-204 induction motor SOP. Symptoms: high winding temperature, rising current, vibration increase, repeated thermal alarms. Likely root causes: bearing lubrication loss, bl
- maintenance_history.csv | MTR-204 | motor | history | Historical maintenance record for MTR-204. Date: 2026-05-02 09:30:00. Issue: Motor temperature rising. Action: Cleaned cooling fins and checked bearing grease. Result: Temporary im
- incident_records.csv | MTR-204 | motor | incident | Incident record for MTR-204. Severity: High. Incident: Temperature crossed high alarm during peak load. Recommended response: Inspect bearing and cooling path.

In [7]:
# ============================================================
# Cell 6: Load open-source local LLM - CPU safe
# ============================================================

MODEL_ID = "Qwen/Qwen2.5-0.5B-Instruct"
DEVICE = "cpu"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

llm = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

llm.to(DEVICE)
llm.eval()

def generate_llm_response(system_prompt, user_prompt, max_new_tokens=180):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1800).to(DEVICE)

    with torch.no_grad():
        output = llm.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.03,
            pad_token_id=tokenizer.eos_token_id,
        )

    new_tokens = output[0][inputs["input_ids"].shape[-1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

print(generate_llm_response(
    "You are a maintenance assistant.",
    "Explain motor overheating in 2 short bullets.",
    max_new_tokens=80,
))

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Motor overheating can occur due to several reasons, including:

1. Overloading: When the motor is overloaded, it draws more current than it can handle, leading to increased heat generation.

2. Insufficient cooling: If the motor is not properly cooled, it can overheat due to lack of proper airflow or cooling mechanisms.

In [8]:
# ============================================================
# Cell 7: Agentic backend using steel app model only
# ============================================================

USE_LLM_REWRITE = True
LLM_MAX_NEW_TOKENS = 140

sensor_scored = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv")
asset_health = pd.read_csv(f"{DATA_DIR}/asset_health_summary.csv")
history_df = pd.read_csv(f"{DATA_DIR}/maintenance_history.csv")
failure_reports_df = pd.read_csv(f"{DATA_DIR}/failure_reports.csv")
spares_df = pd.read_csv(f"{DATA_DIR}/spares_inventory.csv")
delay_logs_df = pd.read_csv(f"{DATA_DIR}/delay_logs.csv")

ASSET_IDS = sorted(asset_health["asset_id"].unique().tolist())
SESSION_MEMORY = {"last_asset_id": None, "last_top_asset": None, "last_asset_ids": [], "last_mode": None, "turns": []}

def _read_csv_safe(path):
    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()

def _to_float(x, default=0.0):
    try:
        if pd.isna(x):
            return default
        return float(x)
    except Exception:
        return default

def extract_asset_ids(query):
    q = str(query).upper()
    found = [a for a in ASSET_IDS if a.upper() in q]

    if not found and re.search(r"\b(same asset|same equipment|that asset|that equipment|it)\b", q, re.I):
        if SESSION_MEMORY.get("last_top_asset"):
            found = [SESSION_MEMORY["last_top_asset"]]
        elif SESSION_MEMORY.get("last_asset_id"):
            found = [SESSION_MEMORY["last_asset_id"]]

    return list(dict.fromkeys(found))

def get_latest_sensor_summary(asset_id):
    row = asset_health[asset_health["asset_id"] == asset_id]
    if row.empty:
        return {"asset_id": asset_id, "error": "No sensor data found."}
    r = row.iloc[0].to_dict()
    return {
        "asset_id": asset_id,
        "asset_type": r.get("asset_type"),
        "area": r.get("area"),
        "criticality": r.get("criticality"),
        "temperature_latest": round(_to_float(r.get("temperature")), 2),
        "vibration_latest": round(_to_float(r.get("vibration")), 2),
        "current_latest": round(_to_float(r.get("current")), 2),
        "pressure_latest": round(_to_float(r.get("pressure")), 2),
        "rpm_latest": round(_to_float(r.get("rpm")), 2),
        "alarm_count_latest": int(_to_float(r.get("alarm_count"))),
        "failure_risk_latest": round(_to_float(r.get("failure_risk")), 4),
        "failure_pred": int(_to_float(r.get("failure_pred"), 0)),
        "risk_band": r.get("risk_band"),
        "estimated_rul_days": round(_to_float(r.get("estimated_rul_days"), 30), 1),
        "anomaly_events_24h": int(_to_float(r.get("anomaly_events_24h"))),
        "temperature_slope_24h": round(_to_float(r.get("temperature_slope_24h")), 4),
        "vibration_slope_24h": round(_to_float(r.get("vibration_slope_24h")), 4),
        "pressure_slope_24h": round(_to_float(r.get("pressure_slope_24h")), 4),
    }

def detect_anomaly(asset_id):
    s = get_latest_sensor_summary(asset_id)
    risk = s.get("failure_risk_latest", 0)
    events = s.get("anomaly_events_24h", 0)

    if risk >= 0.75 or events >= 6:
        level = "HIGH"
    elif risk >= 0.45 or events >= 2:
        level = "MEDIUM"
    else:
        level = "LOW"

    return {"asset_id": asset_id, "anomaly_level": level, "failure_risk": risk, "anomaly_events_24h": events}

def get_past_work_orders(asset_id):
    return history_df[history_df["asset_id"] == asset_id].tail(4).to_dict("records")

def get_failure_reports(asset_id):
    return failure_reports_df[failure_reports_df["asset_id"] == asset_id].tail(4).to_dict("records")

def get_spares(asset_id):
    return spares_df[spares_df["asset_id"] == asset_id].to_dict("records")

def get_delay(asset_id):
    df = delay_logs_df[delay_logs_df["asset_id"] == asset_id]
    if df.empty:
        return {"delay_hours": 0, "production_impact": "low"}
    return df.iloc[-1].to_dict()

def get_relevant_feedback(asset_id):
    fb = _read_csv_safe(f"{DATA_DIR}/feedback_log.csv")
    if fb.empty or "asset_id" not in fb.columns:
        return []
    return fb[fb["asset_id"] == asset_id].tail(3).to_dict("records")

def prioritize_action(sensor, anomaly, spares, delay):
    risk = sensor.get("failure_risk_latest", 0)
    rul = sensor.get("estimated_rul_days", 30)
    criticality = sensor.get("criticality", "medium")
    delay_hours = _to_float(delay.get("delay_hours", 0))
    spare_blocked = any(_to_float(s.get("stock_qty", 0)) <= 0 and _to_float(s.get("lead_time_days", 0)) >= 7 for s in spares)

    score = risk * 45
    score += {"critical": 18, "high": 12, "medium": 7, "low": 2}.get(criticality, 7)
    score += {"HIGH": 12, "MEDIUM": 6, "LOW": 0}.get(anomaly.get("anomaly_level", "LOW"), 0)
    score += min(delay_hours * 2.5, 15)
    score += 8 if rul <= 3 else 4 if rul <= 7 else 0
    score += 5 if spare_blocked else 0

    if score >= 72:
        return {"priority": "P1", "risk_level": "CRITICAL", "urgency": "Immediate action", "priority_score": round(score, 2)}
    if score >= 55:
        return {"priority": "P2", "risk_level": "HIGH", "urgency": "Action within 24 hours", "priority_score": round(score, 2)}
    if score >= 38:
        return {"priority": "P3", "risk_level": "MEDIUM", "urgency": "Plan in maintenance window", "priority_score": round(score, 2)}
    return {"priority": "P4", "risk_level": "LOW", "urgency": "Monitor only", "priority_score": round(score, 2)}

def infer_root_cause(asset_id, sensor, history, failures):
    typ = str(sensor.get("asset_type", "")).lower()
    causes = []

    if "motor" in typ or sensor.get("temperature_latest", 0) >= 80:
        causes.append("bearing lubrication degradation, cooling restriction, overload, or current imbalance")
    if "gearbox" in typ or sensor.get("vibration_latest", 0) >= 7:
        causes.append("bearing wear, gear tooth wear, shaft misalignment, oil contamination, or foundation looseness")
    if "pump" in typ:
        causes.append("suction restriction, low tank level, air ingress, seal wear, or impeller wear")
    if "hydraulic" in typ or sensor.get("pressure_latest", 9) < 6:
        causes.append("filter choking, relief valve drift, internal leakage, or pump wear")

    return "; ".join(dict.fromkeys(causes)) or "degradation inferred from risk model, anomaly pattern, and history"

def recommended_actions(asset_id, sensor, feedback):
    fb_text = " ".join([str(x.get("corrected_action", "")) + " " + str(x.get("feedback_text", "")) for x in feedback]).lower()
    actions = []

    if "lubrication" in fb_text:
        actions.append("Apply learned feedback: inspect bearing lubrication first.")
    if "alignment" in fb_text:
        actions.append("Apply learned feedback: verify alignment early in the inspection.")

    typ = str(sensor.get("asset_type", "")).lower()
    if "gearbox" in typ:
        actions += ["Check oil contamination and level.", "Inspect alignment, bearing condition, gear mesh, and foundation bolts."]
    elif "pump" in typ:
        actions += ["Check suction strainer, tank level, air ingress, seal leakage, and impeller condition."]
    elif "hydraulic" in typ:
        actions += ["Check filter differential pressure, oil contamination, relief valve setting, pump leakage, and actuator response."]
    else:
        actions += ["Inspect bearing lubrication, cooling airflow, current imbalance, load, and coupling alignment."]

    return list(dict.fromkeys(actions))

def spares_strategy(spares):
    if not spares:
        return "- No spare record found. Verify store inventory."
    lines = []
    for s in spares:
        qty = int(_to_float(s.get("stock_qty", 0)))
        lead = int(_to_float(s.get("lead_time_days", 0)))
        part = s.get("spare_part", "spare")
        if qty > 0:
            lines.append(f"- {part}: stock {qty}, lead time {lead} days. Reserve before shutdown.")
        else:
            lines.append(f"- {part}: stock 0, procure immediately, lead time {lead} days.")
    return "\n".join(lines)

def format_records(records):
    if not records:
        return "- No matching records found."
    return "\n".join(["- " + "; ".join([f"{k}: {v}" for k, v in r.items()]) for r in records[:3]])

def format_sources(docs):
    if not docs:
        return "- No retrieved source."
    lines = []
    for i, d in enumerate(docs[:5], 1):
        txt = re.sub(r"\s+", " ", d["text"]).strip()[:260]
        lines.append(f"{i}. {d['source']} ({d.get('equipment_type')}/{d.get('issue_type')}): {txt}")
    return "\n".join(lines)

def write_logbook(query, asset_id, priority, summary, user_id="demo_user"):
    path = f"{DATA_DIR}/digital_logbook.csv"
    df = _read_csv_safe(path)
    row = {
        "timestamp": datetime.now().isoformat(),
        "user_id": user_id,
        "asset_id": asset_id,
        "query": query,
        "risk_level": priority.get("risk_level", ""),
        "priority": priority.get("priority", ""),
        "summary": str(summary)[:1000],
    }
    pd.concat([df, pd.DataFrame([row])], ignore_index=True).to_csv(path, index=False)

def save_feedback(query=None, asset_id=None, feedback_type="accepted", feedback_text="", corrected_action="", outcome="", user_id=None, user=None, **kwargs):
    path = f"{DATA_DIR}/feedback_log.csv"
    df = _read_csv_safe(path)
    row = {
        "timestamp": datetime.now().isoformat(),
        "user_id": user_id or user or "unknown_user",
        "asset_id": asset_id or SESSION_MEMORY.get("last_asset_id", ""),
        "query": query or "",
        "feedback_type": feedback_type,
        "feedback_text": feedback_text or kwargs.get("engineer_feedback", ""),
        "corrected_action": corrected_action or kwargs.get("recommendation", ""),
        "outcome": outcome,
    }
    pd.concat([df, pd.DataFrame([row])], ignore_index=True).to_csv(path, index=False)
    return row

def llm_engineer_explanation(facts):
    system = "You are a steel plant maintenance copilot. Write only 3 short bullets. Do not invent numbers."
    user = f"Use only these locked facts:\n{json.dumps(facts, indent=2, ensure_ascii=False)}"
    try:
        text = generate_llm_response(system, user, max_new_tokens=LLM_MAX_NEW_TOKENS)
        if re.search(r"\b(year|month|mpa|g/m)\b", text, re.I) or len(text.strip()) < 40:
            return "LLM explanation constrained: follow the locked fields above."
        return text.strip()
    except Exception as e:
        return f"LLM explanation unavailable; deterministic report remains valid. Error: {e}"

def build_agent_trace(asset_id, sensor, anomaly, priority, docs):
    return [
        {"agent": "Triage Agent", "decision": f"Detected asset {asset_id} and equipment type {sensor.get('asset_type')}."},
        {"agent": "Sensor Agent", "decision": f"Failure risk {sensor.get('failure_risk_latest')}, anomaly level {anomaly.get('anomaly_level')}, RUL {sensor.get('estimated_rul_days')} days."},
        {"agent": "Knowledge Agent", "decision": f"Retrieved {len(docs)} filtered evidence chunks."},
        {"agent": "Risk Agent", "decision": f"Assigned {priority.get('priority')} / {priority.get('risk_level')}."},
        {"agent": "Planning Agent", "decision": "Generated work order actions and spare strategy."},
        {"agent": "Reporting Agent", "decision": "Generated alert and logbook entry."},
    ]

def deterministic_report(query, asset_id):
    sensor = get_latest_sensor_summary(asset_id)
    anomaly = detect_anomaly(asset_id)
    history = get_past_work_orders(asset_id)
    failures = get_failure_reports(asset_id)
    spares = get_spares(asset_id)
    delay = get_delay(asset_id)
    feedback = get_relevant_feedback(asset_id)
    priority = prioritize_action(sensor, anomaly, spares, delay)
    root = infer_root_cause(asset_id, sensor, history, failures)
    actions = recommended_actions(asset_id, sensor, feedback)
    docs = retrieve_docs(query, top_k=5, asset_id=asset_id, equipment_type=sensor.get("asset_type"))
    trace = build_agent_trace(asset_id, sensor, anomaly, priority, docs)

    facts = {
        "asset_id": asset_id,
        "risk_level": priority["risk_level"],
        "priority": priority["priority"],
        "rul_days": sensor["estimated_rul_days"],
        "failure_risk": sensor["failure_risk_latest"],
        "source_count": len(docs),
    }
    llm_note = llm_engineer_explanation(facts) if USE_LLM_REWRITE else ""

    report = f"""
**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: {asset_id}
- Equipment type: {sensor.get("asset_type")}
- Area: {sensor.get("area")}
- Criticality: {sensor.get("criticality")}
- Risk level: {priority.get("risk_level")}
- Priority: {priority.get("priority")} - {priority.get("urgency")}
- Failure risk: {sensor.get("failure_risk_latest")}
- RUL / remaining useful life: {sensor.get("estimated_rul_days")} days

**Diagnosis**
- The asset shows {anomaly.get("anomaly_level")} abnormality based on sensor trend, anomaly events, and steel app failure-risk prediction.

**Root Cause**
- Probable root cause: {root}.

**Risk and RUL Explanation**
- RUL is reduced by steel model failure probability, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: {sensor.get("temperature_slope_24h")}
- Vibration slope 24h: {sensor.get("vibration_slope_24h")}
- Pressure slope 24h: {sensor.get("pressure_slope_24h")}

**Immediate Actions**
{chr(10).join([f"- {a}" for a in actions])}

**Spare Strategy**
{spares_strategy(spares)}

**Evidence / Sources**
Historical work orders:
{format_records(history)}

Failure reports:
{format_records(failures)}

Retrieved evidence:
{format_sources(docs)}

**Previous Engineer Feedback Used**
{format_records(feedback)}

**Agent Reasoning Trace**
{chr(10).join([f"- {t['agent']}: {t['decision']}" for t in trace])}

**LLM Engineer Explanation**
{llm_note}

**Alert / Logbook Note**
- Alert: {priority.get("risk_level")} risk for {asset_id}; {priority.get("urgency")}.
- Digital logbook entry created for follow-up.
""".strip()

    return {
        "asset_id": asset_id,
        "sensor_summary": sensor,
        "anomaly_result": anomaly,
        "risk_priority": priority,
        "priority": f"{priority.get('priority')} - {priority.get('urgency')}",
        "history": history,
        "failure_reports": failures,
        "spares": spares,
        "delay": delay,
        "feedback_used": feedback,
        "retrieved_docs": docs,
        "retrieved_knowledge": docs,
        "agent_trace": trace,
        "alert_report": f"Alert for {asset_id}: {priority.get('risk_level')} risk, {priority.get('priority')}, RUL {sensor.get('estimated_rul_days')} days.",
        "answer": report,
        "final_answer": report,
        "llm_used": True,
        "llm_validation": "locked_fields_plus_llm_explanation",
    }

def plant_priority_report(query, asset_ids=None):
    asset_ids = asset_ids or ASSET_IDS
    rows = []

    for asset_id in asset_ids:
        sensor = get_latest_sensor_summary(asset_id)
        anomaly = detect_anomaly(asset_id)
        spares = get_spares(asset_id)
        delay = get_delay(asset_id)
        priority = prioritize_action(sensor, anomaly, spares, delay)
        rows.append({
            "asset_id": asset_id,
            "asset_type": sensor.get("asset_type"),
            "area": sensor.get("area"),
            "criticality": sensor.get("criticality"),
            "failure_risk": sensor.get("failure_risk_latest"),
            "rul_days": sensor.get("estimated_rul_days"),
            "risk_level": priority.get("risk_level"),
            "priority": priority.get("priority"),
            "priority_score": priority.get("priority_score"),
            "urgency": priority.get("urgency"),
            "delay_hours": delay.get("delay_hours", 0),
        })

    table = pd.DataFrame(rows).sort_values(["priority_score", "failure_risk"], ascending=False).reset_index(drop=True)
    top_asset = table.iloc[0]["asset_id"]

    SESSION_MEMORY["last_asset_id"] = top_asset
    SESSION_MEMORY["last_top_asset"] = top_asset
    SESSION_MEMORY["last_asset_ids"] = list(asset_ids)
    SESSION_MEMORY["last_mode"] = "plant_priority"

    docs = retrieve_docs(query, top_k=5, plant_level=True)
    ranking = "\n".join([
        f"- {r.asset_id}: {r.priority}/{r.risk_level}, score {r.priority_score}, failure risk {r.failure_risk}, RUL {r.rul_days} days, criticality {r.criticality}, delay {r.delay_hours}h"
        for r in table.itertuples()
    ])

    llm_note = llm_engineer_explanation({"top_asset": top_asset, "assets_ranked": table.head(5).to_dict("records")})

    report = f"""
**Plant-Level Maintenance Decision Summary**

**Locked Decision Fields**
- Most urgent asset: {top_asset}
- Ranking basis: criticality, delay severity, steel model failure risk, RUL, anomaly status, spares/procurement.

**Diagnosis**
- Plant equipment was compared across {len(asset_ids)} demo steel assets.

**Root Cause**
- Priority is driven by degradation, production bottleneck impact, criticality, and maintenance constraints.

**Risk and RUL**
{ranking}

**Immediate Actions**
- Create first work order for {top_asset}.
- Reserve spares before shutdown.
- Notify area supervisor for P1/P2 assets.
- Continue monitoring lower-ranked assets.

**Spare Strategy**
- Review spare inventory for {top_asset}; if any critical item has zero stock or high lead time, raise procurement immediately.

**Evidence / Sources**
{format_sources(docs)}

**Agent Reasoning Trace**
- Triage Agent: identified plant-level prioritization request.
- Sensor Agent: collected latest health and RUL for all demo steel assets.
- Risk Agent: ranked assets by risk, criticality, delay, and RUL.
- Planning Agent: selected {top_asset} as first maintenance target.
- Reporting Agent: generated supervisor summary and logbook entry.

**LLM Engineer Explanation**
{llm_note}

**Alert / Logbook Note**
- Plant alert generated. Recommended first action is on {top_asset}.
""".strip()

    priority = {"priority": "PLANT", "risk_level": "PLANT_SUMMARY", "urgency": f"Prioritize {top_asset}", "priority_score": float(table.iloc[0]["priority_score"])}
    write_logbook(query, top_asset, priority, report)

    return {
        "mode": "plant_priority",
        "asset_id": top_asset,
        "asset_ids": list(asset_ids),
        "plant_priority_table": table.to_dict("records"),
        "risk_priority": priority,
        "priority": "Plant priority summary",
        "anomaly_result": {},
        "retrieved_docs": docs,
        "retrieved_knowledge": docs,
        "alert_report": f"Plant alert: prioritize {top_asset}.",
        "answer": report,
        "final_answer": report,
        "llm_used": True,
        "llm_validation": "locked_fields_plus_llm_explanation",
    }

def data_source_report(query):
    docs = retrieve_docs(query, top_k=5, equipment_type="public_dataset", plant_level=True)
    report = f"""
**Data Source and Model Separation Summary**

**Public Benchmark**
- Public dataset: AI4I 2020 Predictive Maintenance Dataset from UCI.
- Used for: validating the predictive-maintenance modelling pipeline.
- Important note: vibration, current, and pressure are engineered proxy features mapped into the common schema.

**Steel Demo Layer**
- Used for: Tata Steel-style maintenance decisions, SOP retrieval, spares, delay logs, feedback, alerts, and digital logbook.
- Demo decisions use the separate steel model, not the public benchmark model.

**Evidence / Sources**
{format_sources(docs)}
""".strip()
    return {"asset_id": None, "answer": report, "final_answer": report, "llm_used": True, "llm_validation": "data_source_report"}

def maintenance_agent(user_query, role="maintenance_engineer", user_id="demo_user", write_log=True, use_llm=True):
    if re.search(r"\b(public dataset|ai4i|uci|data source|dataset)\b", user_query, re.I):
        return data_source_report(user_query)

    asset_ids = extract_asset_ids(user_query)
    plant_query = re.search(r"\b(compare|plant|supervisor|summary|priority|prioritize|bottleneck|most urgent|today|all equipment)\b", user_query, re.I)

    if len(asset_ids) > 1:
        result = plant_priority_report(user_query, asset_ids)
    elif len(asset_ids) == 0 and plant_query:
        result = plant_priority_report(user_query, ASSET_IDS)
    elif len(asset_ids) == 0:
        result = {
            "asset_id": None,
            "priority": "Unknown",
            "answer": "Please mention an asset ID such as MTR-204, GBX-17, PMP-09, or HPP-12, or ask for plant priority.",
            "final_answer": "Please mention an asset ID such as MTR-204, GBX-17, PMP-09, or HPP-12, or ask for plant priority.",
            "llm_used": True,
        }
    else:
        asset_id = asset_ids[0]
        SESSION_MEMORY["last_asset_id"] = asset_id
        SESSION_MEMORY["last_top_asset"] = asset_id
        SESSION_MEMORY["last_mode"] = "asset_report"
        result = deterministic_report(user_query, asset_id)
        if write_log:
            write_logbook(user_query, asset_id, result["risk_priority"], result["answer"], user_id=user_id)

    SESSION_MEMORY["turns"].append({"timestamp": datetime.now().isoformat(), "query": user_query, "asset_ids": asset_ids})
    return result

def ingest_new_sensor_alert(asset_id, temperature, vibration, current, pressure, rpm=1480, alarm_count=2, user_id="iot_gateway"):
    global sensor_scored, asset_health

    base = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv")
    raw = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs.csv")
    info = raw[raw["asset_id"] == asset_id].iloc[-1].to_dict()

    row = {
        "timestamp": datetime.now().isoformat(),
        "asset_id": asset_id,
        "asset_type": info.get("asset_type"),
        "area": info.get("area"),
        "criticality": info.get("criticality"),
        "temperature": temperature,
        "vibration": vibration,
        "current": current,
        "pressure": pressure,
        "rpm": rpm,
        "alarm_count": alarm_count,
        "maintenance_event": 0,
        "failure_in_7d": 0,
        "source_dataset": "Synthetic_steel_plant_layer",
        "source_public": 0,
        "is_demo_asset": 1,
        "failure_mode": "real_time_alert",
    }

    raw = pd.concat([raw, pd.DataFrame([row])], ignore_index=True)
    raw.to_csv(f"{DATA_DIR}/steel_sensor_logs.csv", index=False)

    X_new = pd.DataFrame([row])[feature_cols]
    row["anomaly_score"] = float(-steel_anomaly_model.decision_function(X_new)[0])
    row["is_anomaly"] = int(steel_anomaly_model.predict(X_new)[0] == -1)
    row["failure_risk"] = float(steel_risk_model.predict_proba(X_new)[0, 1])
    row["failure_pred"] = int(row["failure_risk"] >= STEEL_THRESHOLD)
    row["risk_band"] = "CRITICAL" if row["failure_risk"] >= 0.75 else "HIGH" if row["failure_risk"] >= 0.5 else "MEDIUM" if row["failure_risk"] >= 0.25 else "LOW"
    row["anomaly_events_24h"] = int(base[base["asset_id"] == asset_id].tail(23)["is_anomaly"].sum() + row["is_anomaly"])
    row["temperature_slope_24h"] = 0
    row["vibration_slope_24h"] = 0
    row["pressure_slope_24h"] = 0
    row["current_slope_24h"] = 0
    row["estimated_rul_days"] = max(1.0, round(50 * (1 - row["failure_risk"]) - row["anomaly_events_24h"] * 0.55, 1))

    base = pd.concat([base, pd.DataFrame([row])], ignore_index=True)
    base.to_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv", index=False)
    base.to_csv(f"{DATA_DIR}/sensor_logs_scored.csv", index=False)

    asset_health = base.sort_values("timestamp").groupby("asset_id").tail(1)
    asset_health.to_csv(f"{DATA_DIR}/asset_health_summary.csv", index=False)
    sensor_scored = base

    return maintenance_agent(f"New real-time alert for {asset_id}. Diagnose and generate alert report.", user_id=user_id)

print("Agent backend loaded.")
print("Demo steel assets:", ASSET_IDS)
print("Steel app threshold:", STEEL_THRESHOLD)

Agent backend loaded.
Demo steel assets: ['GBX-17', 'HPP-12', 'MTR-204', 'PMP-09']
Steel app threshold: 0.04382305057411851

In [9]:
# ============================================================
# Cell 7B: Hybrid decision labels + rule-score breakdown
# ============================================================

sensor_scored = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv")
asset_health = pd.read_csv(f"{DATA_DIR}/asset_health_summary.csv")
ASSET_IDS = sorted(asset_health["asset_id"].unique().tolist())

def safe_float(x, default=0.0):
    try:
        if pd.isna(x):
            return default
        return float(x)
    except Exception:
        return default

def get_latest_sensor_summary(asset_id):
    row = asset_health[asset_health["asset_id"] == asset_id]
    if row.empty:
        return {"asset_id": asset_id, "error": "No sensor data found."}

    r = row.iloc[0].to_dict()

    return {
        "asset_id": asset_id,
        "asset_type": r.get("asset_type"),
        "area": r.get("area"),
        "criticality": r.get("criticality"),
        "temperature_latest": round(safe_float(r.get("temperature")), 2),
        "vibration_latest": round(safe_float(r.get("vibration")), 2),
        "current_latest": round(safe_float(r.get("current")), 2),
        "pressure_latest": round(safe_float(r.get("pressure")), 2),
        "rpm_latest": round(safe_float(r.get("rpm")), 2),
        "alarm_count_latest": int(safe_float(r.get("alarm_count"))),
        "ml_failure_risk_latest": round(safe_float(r.get("ml_failure_risk")), 4),
        "operational_rule_score": round(safe_float(r.get("operational_rule_score")), 2),
        "hybrid_health_score": round(safe_float(r.get("hybrid_health_score")), 2),
        "hybrid_failure_risk": round(safe_float(r.get("hybrid_failure_risk", r.get("failure_risk"))), 4),
        "failure_risk_latest": round(safe_float(r.get("hybrid_failure_risk", r.get("failure_risk"))), 4),
        "failure_pred": int(safe_float(r.get("failure_pred"), 0)),
        "risk_band": r.get("risk_band"),
        "estimated_rul_days": round(safe_float(r.get("estimated_rul_days"), 30), 1),
        "anomaly_events_24h": int(safe_float(r.get("anomaly_events_24h"))),
        "temperature_slope_24h": round(safe_float(r.get("temperature_slope_24h")), 4),
        "vibration_slope_24h": round(safe_float(r.get("vibration_slope_24h")), 4),
        "pressure_slope_24h": round(safe_float(r.get("pressure_slope_24h")), 4),
    }

def operational_rule_breakdown(sensor, delay=None, spares=None):
    delay = delay or {}
    spares = spares or []

    reasons = []
    typ = str(sensor.get("asset_type", "")).lower()
    criticality = str(sensor.get("criticality", "medium")).lower()

    temp = safe_float(sensor.get("temperature_latest"))
    vib = safe_float(sensor.get("vibration_latest"))
    current = safe_float(sensor.get("current_latest"))
    pressure = safe_float(sensor.get("pressure_latest"), 8)
    alarms = safe_float(sensor.get("alarm_count_latest"))
    anomalies = safe_float(sensor.get("anomaly_events_24h"))
    delay_hours = safe_float(delay.get("delay_hours", 0))

    if "gearbox" in typ:
        if vib >= 7:
            reasons.append("Gearbox vibration >= 7 mm/s: +30")
        if vib >= 9:
            reasons.append("Gearbox vibration >= 9 mm/s: +20")
        if vib >= 10:
            reasons.append("Gearbox vibration >= 10 mm/s: +10")
        if temp >= 65:
            reasons.append("Gearbox temperature >= 65 deg C: +8")

    if "motor" in typ:
        if temp >= 80:
            reasons.append("Motor temperature >= 80 deg C: +25")
        if temp >= 85:
            reasons.append("Motor temperature >= 85 deg C: +15")
        if current >= 80:
            reasons.append("Motor current >= 80 A: +12")
        if vib >= 5:
            reasons.append("Motor vibration >= 5 mm/s: +8")

    if "pump" in typ:
        if pressure <= 6:
            reasons.append("Pump pressure <= 6 bar: +22")
        if vib >= 5:
            reasons.append("Pump vibration >= 5 mm/s: +12")
        if current >= 75:
            reasons.append("Pump current >= 75 A: +8")

    if "hydraulic" in typ:
        if pressure <= 6:
            reasons.append("Hydraulic pressure <= 6 bar: +25")
        if temp >= 65:
            reasons.append("Hydraulic oil temperature >= 65 deg C: +10")
        if alarms >= 2:
            reasons.append("Hydraulic alarm count >= 2: +8")

    if alarms >= 2:
        reasons.append("Alarm count >= 2: +8")
    if alarms >= 4:
        reasons.append("Alarm count >= 4: +8")
    if anomalies >= 6:
        reasons.append("Anomaly events >= 6 in last 24h: +15")
    if anomalies >= 18:
        reasons.append("Anomaly events >= 18 in last 24h: +10")

    if criticality == "critical":
        reasons.append("Critical equipment: +15")
    elif criticality == "high":
        reasons.append("High criticality equipment: +10")
    elif criticality == "medium":
        reasons.append("Medium criticality equipment: +5")

    if delay_hours > 0:
        reasons.append(f"Historical delay impact {delay_hours} hours: +{min(delay_hours * 2.0, 12):.1f}")

    spare_blocked = any(safe_float(s.get("stock_qty", 0)) <= 0 and safe_float(s.get("lead_time_days", 0)) >= 7 for s in spares)
    if spare_blocked:
        reasons.append("Critical spare unavailable with high lead time: priority uplift")

    if not reasons:
        reasons.append("No major rule trigger; monitor based on trend and ML signal.")

    return reasons

def detect_anomaly(asset_id):
    s = get_latest_sensor_summary(asset_id)
    health = s.get("hybrid_health_score", 0)
    events = s.get("anomaly_events_24h", 0)

    if health >= 75 or events >= 12:
        level = "HIGH"
    elif health >= 55 or events >= 4:
        level = "MEDIUM"
    else:
        level = "LOW"

    return {
        "asset_id": asset_id,
        "anomaly_level": level,
        "hybrid_failure_risk": s.get("hybrid_failure_risk", 0),
        "ml_failure_risk": s.get("ml_failure_risk_latest", 0),
        "operational_rule_score": s.get("operational_rule_score", 0),
        "hybrid_health_score": health,
        "anomaly_events_24h": events,
    }

def prioritize_action(sensor, anomaly, spares, delay):
    health = sensor.get("hybrid_health_score", 0)
    rul = sensor.get("estimated_rul_days", 30)
    delay_hours = safe_float(delay.get("delay_hours", 0))
    spare_blocked = any(safe_float(s.get("stock_qty", 0)) <= 0 and safe_float(s.get("lead_time_days", 0)) >= 7 for s in spares)

    score = health
    score += min(delay_hours * 1.5, 8)
    score += 5 if rul <= 3 else 3 if rul <= 7 else 0
    score += 4 if spare_blocked else 0
    score = round(float(np.clip(score, 0, 100)), 2)

    if score >= 75:
        return {"priority": "P1", "risk_level": "CRITICAL", "urgency": "Immediate action", "priority_score": score}
    if score >= 55:
        return {"priority": "P2", "risk_level": "HIGH", "urgency": "Action within 24 hours", "priority_score": score}
    if score >= 38:
        return {"priority": "P3", "risk_level": "MEDIUM", "urgency": "Plan in maintenance window", "priority_score": score}
    return {"priority": "P4", "risk_level": "LOW", "urgency": "Monitor only", "priority_score": score}

def deterministic_report(query, asset_id):
    sensor = get_latest_sensor_summary(asset_id)
    anomaly = detect_anomaly(asset_id)
    history = get_past_work_orders(asset_id)
    failures = get_failure_reports(asset_id)
    spares = get_spares(asset_id)
    delay = get_delay(asset_id)
    feedback = get_relevant_feedback(asset_id)
    priority = prioritize_action(sensor, anomaly, spares, delay)
    root = infer_root_cause(asset_id, sensor, history, failures)
    actions = recommended_actions(asset_id, sensor, feedback)
    docs = retrieve_docs(query, top_k=5, asset_id=asset_id, equipment_type=sensor.get("asset_type"))
    trace = build_agent_trace(asset_id, sensor, anomaly, priority, docs)
    rule_reasons = operational_rule_breakdown(sensor, delay, spares)

    facts = {
        "asset_id": asset_id,
        "risk_level": priority["risk_level"],
        "priority": priority["priority"],
        "rul_days": sensor["estimated_rul_days"],
        "hybrid_failure_risk": sensor["hybrid_failure_risk"],
        "ml_failure_risk": sensor["ml_failure_risk_latest"],
        "operational_rule_score": sensor["operational_rule_score"],
        "source_count": len(docs),
    }

    llm_note = llm_engineer_explanation(facts) if USE_LLM_REWRITE else ""

    report = f"""
**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: {asset_id}
- Equipment type: {sensor.get("asset_type")}
- Area: {sensor.get("area")}
- Criticality: {sensor.get("criticality")}
- Risk level: {priority.get("risk_level")}
- Priority: {priority.get("priority")} - {priority.get("urgency")}
- Hybrid failure risk: {sensor.get("hybrid_failure_risk")}
- ML failure risk: {sensor.get("ml_failure_risk_latest")}
- Operational rule score: {sensor.get("operational_rule_score")}/100
- Hybrid health score: {sensor.get("hybrid_health_score")}/100
- RUL / remaining useful life: {sensor.get("estimated_rul_days")} days

**Diagnosis**
- The asset shows {anomaly.get("anomaly_level")} abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: {root}.

**Risk Score Explanation**
{chr(10).join([f"- {r}" for r in rule_reasons])}

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: {sensor.get("temperature_slope_24h")}
- Vibration slope 24h: {sensor.get("vibration_slope_24h")}
- Pressure slope 24h: {sensor.get("pressure_slope_24h")}

**Immediate Actions**
{chr(10).join([f"- {a}" for a in actions])}

**Spare Strategy**
{spares_strategy(spares)}

**Evidence / Sources**
Historical work orders:
{format_records(history)}

Failure reports:
{format_records(failures)}

Retrieved evidence:
{format_sources(docs)}

**Previous Engineer Feedback Used**
{format_records(feedback)}

**Agent Reasoning Trace**
{chr(10).join([f"- {t['agent']}: {t['decision']}" for t in trace])}

**LLM Engineer Explanation**
{llm_note}

**Alert / Logbook Note**
- Alert: {priority.get("risk_level")} risk for {asset_id}; {priority.get("urgency")}.
- Digital logbook entry created for follow-up.
""".strip()

    return {
        "asset_id": asset_id,
        "sensor_summary": sensor,
        "anomaly_result": anomaly,
        "risk_priority": priority,
        "priority": f"{priority.get('priority')} - {priority.get('urgency')}",
        "history": history,
        "failure_reports": failures,
        "spares": spares,
        "delay": delay,
        "feedback_used": feedback,
        "rule_breakdown": rule_reasons,
        "retrieved_docs": docs,
        "retrieved_knowledge": docs,
        "agent_trace": trace,
        "alert_report": f"Alert for {asset_id}: {priority.get('risk_level')} risk, {priority.get('priority')}, RUL {sensor.get('estimated_rul_days')} days.",
        "answer": report,
        "final_answer": report,
        "llm_used": True,
        "llm_validation": "locked_fields_plus_llm_explanation",
    }

def plant_priority_report(query, asset_ids=None):
    asset_ids = asset_ids or ASSET_IDS
    rows = []

    for asset_id in asset_ids:
        sensor = get_latest_sensor_summary(asset_id)
        anomaly = detect_anomaly(asset_id)
        spares = get_spares(asset_id)
        delay = get_delay(asset_id)
        priority = prioritize_action(sensor, anomaly, spares, delay)

        rows.append({
            "asset_id": asset_id,
            "asset_type": sensor.get("asset_type"),
            "area": sensor.get("area"),
            "criticality": sensor.get("criticality"),
            "ml_failure_risk": sensor.get("ml_failure_risk_latest"),
            "hybrid_failure_risk": sensor.get("hybrid_failure_risk"),
            "operational_rule_score": sensor.get("operational_rule_score"),
            "hybrid_health_score": sensor.get("hybrid_health_score"),
            "rul_days": sensor.get("estimated_rul_days"),
            "risk_level": priority.get("risk_level"),
            "priority": priority.get("priority"),
            "priority_score": priority.get("priority_score"),
            "urgency": priority.get("urgency"),
            "delay_hours": delay.get("delay_hours", 0),
        })

    table = pd.DataFrame(rows).sort_values(["priority_score", "hybrid_health_score"], ascending=False).reset_index(drop=True)
    top_asset = table.iloc[0]["asset_id"]

    SESSION_MEMORY["last_asset_id"] = top_asset
    SESSION_MEMORY["last_top_asset"] = top_asset
    SESSION_MEMORY["last_asset_ids"] = list(asset_ids)
    SESSION_MEMORY["last_mode"] = "plant_priority"

    docs = retrieve_docs(query, top_k=5, plant_level=True)

    ranking = "\n".join([
        f"- {r.asset_id}: {r.priority}/{r.risk_level}, hybrid score {r.hybrid_health_score}, ML risk {r.ml_failure_risk}, rule score {r.operational_rule_score}, RUL {r.rul_days} days, delay {r.delay_hours}h"
        for r in table.itertuples()
    ])

    llm_note = llm_engineer_explanation({"top_asset": top_asset, "assets_ranked": table.head(5).to_dict("records")})

    report = f"""
**Plant-Level Maintenance Decision Summary**

**Locked Decision Fields**
- Most urgent asset: {top_asset}
- Ranking basis: hybrid ML + operational rule score, criticality, delay severity, RUL, anomaly status, spares/procurement.

**Diagnosis**
- Plant equipment was compared across {len(asset_ids)} demo steel assets.

**Root Cause**
- Priority is driven by degradation, production bottleneck impact, criticality, and maintenance constraints.

**Risk and RUL**
{ranking}

**Immediate Actions**
- Create first work order for {top_asset}.
- Reserve spares before shutdown.
- Notify area supervisor for P1/P2 assets.
- Continue monitoring lower-ranked assets.

**Spare Strategy**
- Review spare inventory for {top_asset}; if any critical item has zero stock or high lead time, raise procurement immediately.

**Evidence / Sources**
{format_sources(docs)}

**Agent Reasoning Trace**
- Triage Agent: identified plant-level prioritization request.
- Sensor Agent: collected latest health and RUL for all demo steel assets.
- Risk Agent: ranked assets by hybrid ML + operational rule score.
- Planning Agent: selected {top_asset} as first maintenance target.
- Reporting Agent: generated supervisor summary and logbook entry.

**LLM Engineer Explanation**
{llm_note}

**Alert / Logbook Note**
- Plant alert generated. Recommended first action is on {top_asset}.
""".strip()

    priority = {
        "priority": "PLANT",
        "risk_level": "PLANT_SUMMARY",
        "urgency": f"Prioritize {top_asset}",
        "priority_score": float(table.iloc[0]["priority_score"]),
    }

    write_logbook(query, top_asset, priority, report)

    return {
        "mode": "plant_priority",
        "asset_id": top_asset,
        "asset_ids": list(asset_ids),
        "plant_priority_table": table.to_dict("records"),
        "risk_priority": priority,
        "priority": "Plant priority summary",
        "anomaly_result": {},
        "retrieved_docs": docs,
        "retrieved_knowledge": docs,
        "alert_report": f"Plant alert: prioritize {top_asset}.",
        "answer": report,
        "final_answer": report,
        "llm_used": True,
        "llm_validation": "locked_fields_plus_llm_explanation",
    }

print("Cell 7B loaded: hybrid risk labels and rule breakdown are now active.")

Cell 7B loaded: hybrid risk labels and rule breakdown are now active.

In [10]:
# ============================================================
# Cell 7C: Patch real-time alert scoring + public dataset query
# Run this after Cell 7B
# ============================================================

def _quick_slope(values):
    values = pd.Series(values).astype(float).dropna().values
    if len(values) < 4:
        return 0.0
    return float(np.polyfit(np.arange(len(values)), values, 1)[0])

def _estimate_rul_from_scored_row(row):
    risk = safe_float(row.get("hybrid_failure_risk", row.get("failure_risk", 0)))
    anomaly_events = safe_float(row.get("anomaly_events_24h", 0))
    criticality = str(row.get("criticality", "medium")).lower()

    rul = 50 * (1 - risk)
    rul -= anomaly_events * 0.45
    rul -= max(0, safe_float(row.get("temperature_slope_24h", 0))) * 4.0
    rul -= max(0, safe_float(row.get("vibration_slope_24h", 0))) * 8.0
    rul -= max(0, -safe_float(row.get("pressure_slope_24h", 0))) * 5.0
    rul -= {"critical": 5, "high": 3, "medium": 1, "low": 0}.get(criticality, 1)

    return round(float(np.clip(rul, 1.0, 60.0)), 1)

def create_sensor_logs_compatibility_file():
    steel_raw = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs.csv")
    steel_raw["source_public"] = 0
    steel_raw["is_demo_asset"] = 1

    public_path = f"{DATA_DIR}/public_ai4i_common_schema.csv"
    if os.path.exists(public_path):
        public_raw = pd.read_csv(public_path)
        public_raw["source_public"] = 1
        public_raw["is_demo_asset"] = 0
        combined = pd.concat([steel_raw, public_raw], ignore_index=True, sort=False)
    else:
        combined = steel_raw.copy()

    combined.to_csv(f"{DATA_DIR}/sensor_logs.csv", index=False)
    return combined

def _refresh_asset_health_from_scored(base):
    global asset_health, sensor_scored, ASSET_IDS

    tmp = base.copy()
    tmp["_parsed_ts"] = pd.to_datetime(tmp["timestamp"], format="mixed", errors="coerce")
    tmp = tmp.sort_values(["asset_id", "_parsed_ts"]).drop(columns=["_parsed_ts"])

    asset_health = (
        tmp.groupby("asset_id")
        .tail(1)
        .sort_values(["hybrid_health_score", "estimated_rul_days"], ascending=[False, True])
        .reset_index(drop=True)
    )

    asset_health.to_csv(f"{DATA_DIR}/asset_health_summary.csv", index=False)
    tmp.to_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv", index=False)
    tmp.to_csv(f"{DATA_DIR}/sensor_logs_scored.csv", index=False)

    sensor_scored = tmp
    ASSET_IDS = sorted(asset_health["asset_id"].unique().tolist())

def ingest_new_sensor_alert(asset_id, temperature, vibration, current, pressure, rpm=1480, alarm_count=2, user_id="iot_gateway"):
    global sensor_scored, asset_health

    base = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs_scored.csv")
    raw = pd.read_csv(f"{DATA_DIR}/steel_sensor_logs.csv")

    asset_rows = raw[raw["asset_id"] == asset_id]
    if asset_rows.empty:
        return {
            "asset_id": asset_id,
            "answer": f"No known asset found for {asset_id}.",
            "final_answer": f"No known asset found for {asset_id}.",
            "priority": "UNKNOWN",
            "anomaly_result": {},
            "alert_report": "No alert generated.",
            "llm_used": False,
        }

    info = asset_rows.iloc[-1].to_dict()

    row = {
        "source": "steel_demo_app",
        "timestamp": datetime.now().isoformat(),
        "asset_id": asset_id,
        "asset_type": info.get("asset_type"),
        "area": info.get("area"),
        "criticality": info.get("criticality"),
        "criticality_score": info.get("criticality_score", 2),
        "temperature": float(temperature),
        "vibration": float(vibration),
        "current": float(current),
        "pressure": float(pressure),
        "rpm": float(rpm),
        "alarm_count": int(alarm_count),
        "delay_hours": info.get("delay_hours", 0),
        "spare_lead_time_days": info.get("spare_lead_time_days", 0),
        "failure_label": 0,
        "failure_mode": "real_time_alert",
    }

    raw = pd.concat([raw, pd.DataFrame([row])], ignore_index=True, sort=False)
    raw.to_csv(f"{DATA_DIR}/steel_sensor_logs.csv", index=False)

    X_new = pd.DataFrame([row])[feature_cols].copy()

    row["ml_failure_risk"] = float(steel_risk_model.predict_proba(X_new)[0, 1])
    row["ml_failure_pred"] = int(row["ml_failure_risk"] >= STEEL_THRESHOLD)
    row["anomaly_score"] = float(-steel_anomaly_model.decision_function(X_new)[0])
    row["is_anomaly"] = int(steel_anomaly_model.predict(X_new)[0] == -1)

    prev = base[base["asset_id"] == asset_id].tail(23).copy()
    row["anomaly_events_24h"] = int(prev["is_anomaly"].sum() + row["is_anomaly"])

    for col in ["temperature", "vibration", "pressure", "current"]:
        row[f"{col}_slope_24h"] = round(_quick_slope(list(prev[col].values) + [row[col]]), 4)

    row["operational_rule_score"] = operational_rule_score(row)
    row["hybrid_health_score"] = round(
        float(np.clip(0.45 * (row["ml_failure_risk"] * 100) + 0.55 * row["operational_rule_score"], 0, 100)),
        2,
    )
    row["hybrid_failure_risk"] = round(row["hybrid_health_score"] / 100, 4)
    row["failure_risk"] = row["hybrid_failure_risk"]
    row["failure_pred"] = int(row["hybrid_health_score"] >= 55)
    row["risk_band"] = risk_band_from_score(row["hybrid_health_score"])
    row["estimated_rul_days"] = _estimate_rul_from_scored_row(row)

    base = pd.concat([base, pd.DataFrame([row])], ignore_index=True, sort=False)
    _refresh_asset_health_from_scored(base)
    create_sensor_logs_compatibility_file()

    return maintenance_agent(
        f"New real-time alert for {asset_id}. Diagnose and generate alert report.",
        user_id=user_id,
    )

def public_dataset_agent_answer(query):
    public_path = f"{DATA_DIR}/public_ai4i_common_schema.csv"
    public_rows = len(pd.read_csv(public_path)) if os.path.exists(public_path) else 0
    steel_rows = len(pd.read_csv(f"{DATA_DIR}/steel_sensor_logs.csv"))

    answer = f"""
**Public Dataset and ML Validation Summary**

**Dataset Used**
- Public benchmark: AI4I 2020 Predictive Maintenance dataset.
- Public rows available: {public_rows}
- Steel demo rows available: {steel_rows}

**How It Is Used**
- AI4I is used as an external benchmark to validate the predictive-maintenance ML pipeline.
- It is not mixed into the steel app decision layer.
- The steel Maintenance Wizard decisions use the steel demo model plus operational rules.

**Leakage Control**
- `Machine failure` is used only as the target label.
- Failure subtype columns such as TWF, HDF, PWF, OSF, and RNF are not used as model features.
- AI4I sensor proxy fields are engineered only from non-target process variables.

**Agent Reasoning Trace**
- Data Agent: checked public benchmark availability.
- ML Agent: separated public validation from steel app scoring.
- Safety Agent: confirmed target leakage is removed.
- Reporting Agent: generated explainable dataset summary.

**Why This Helps The Challenge**
- Shows machine-learning validation on a public predictive-maintenance dataset.
- Keeps industrial decision support explainable, auditable, and domain-safe.
""".strip()

    return {
        "mode": "public_dataset_summary",
        "asset_id": "PUBLIC_AI4I",
        "priority": "Dataset summary",
        "anomaly_result": {},
        "alert_report": "No plant alert; this is a dataset governance response.",
        "answer": answer,
        "final_answer": answer,
        "llm_used": True,
        "llm_validation": "dataset_governance_summary",
    }

if "_BASE_MAINTENANCE_AGENT" not in globals():
    _BASE_MAINTENANCE_AGENT = maintenance_agent

def maintenance_agent(query, user_id="demo_user"):
    q = str(query).lower()
    public_query = any(w in q for w in ["public dataset", "ai4i", "uci", "data source", "dataset used"])
    asset_mentions = query_assets(query) if "query_assets" in globals() else []
    plant_query = any(w in q for w in ["compare", "plant", "supervisor", "prioritize all"])

    if public_query and not asset_mentions and not plant_query:
        return public_dataset_agent_answer(query)

    return _BASE_MAINTENANCE_AGENT(query, user_id=user_id)

create_sensor_logs_compatibility_file()

print("Cell 7C loaded:")
print("- Real-time alerts now receive full hybrid scoring before report generation.")
print("- sensor_logs.csv compatibility file recreated for older test cells.")
print("- Public dataset questions now get a direct governance answer.")

Cell 7C loaded:
- Real-time alerts now receive full hybrid scoring before report generation.
- sensor_logs.csv compatibility file recreated for older test cells.
- Public dataset questions now get a direct governance answer.

In [11]:
# ============================================================
# Cell 8: Backend tests
# ============================================================

queries = [
    "Why is motor MTR-204 overheating and what should I inspect first?",
    "Create a P1 alert report for GBX-17 abnormal vibration.",
    "For PMP-09, check cavitation risk, spare availability, and maintenance plan.",
    "HPP-12 has low hydraulic pressure. Estimate RUL and generate work order.",
    "Compare MTR-204, GBX-17, PMP-09, and HPP-12. Which equipment is most urgent today?",
    "For the same asset, what spare should I arrange next?",
]

for q in queries:
    print("=" * 100)
    print("QUESTION:", q)
    result = maintenance_agent(q)
    print("\nANSWER:\n")
    print(result["answer"])
    print("\nTOOLS USED:")
    print("Asset:", result.get("asset_id", result.get("asset_ids")))
    print("Priority:", result.get("priority"))
    print("Anomaly:", result.get("anomaly_result"))
    print("Alert:", result.get("alert_report"))
    print("LLM used:", result.get("llm_used"))
    print("LLM validation:", result.get("llm_validation"))

====================================================================================================
QUESTION: Why is motor MTR-204 overheating and what should I inspect first?

ANSWER:

**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: MTR-204
- Equipment type: Induction Motor
- Area: Hot Strip Mill
- Criticality: High
- Risk level: CRITICAL
- Priority: P1 - Immediate action
- Hybrid failure risk: 0.7778
- ML failure risk: 0.5063
- Operational rule score: 100.0/100
- Hybrid health score: 77.78/100
- RUL / remaining useful life: 1.0 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: bearing lubrication degradation, cooling restriction, overload, or current imbalance.

**Risk Score Explanation**
- Motor temperature >= 80 deg C: +25
- Motor temperature >= 85 deg C: +15
- Motor current >= 80 A: +12
- Motor vibration >= 5 mm/s: +8
- Alarm count >= 2: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- High criticality equipment: +10
- Historical delay impact 3.5 hours: +7.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.1833
- Vibration slope 24h: 0.0158
- Pressure slope 24h: -0.0065

**Immediate Actions**
- Inspect bearing lubrication, cooling airflow, current imbalance, load, and coupling alignment.

**Spare Strategy**
- DE bearing 6312: stock 2, lead time 5 days. Reserve before shutdown.
- Cooling fan kit: stock 1, lead time 7 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1001; asset_id: MTR-204; timestamp: 2026-05-02 09:30:00; issue: Motor temperature rising; action_taken: Cleaned cooling fins and checked bearing grease; result: Temporary improvement; downtime_hours: 2.0

Failure reports:
- report_id: FR-201; asset_id: MTR-204; timestamp: 2026-04-18 07:45:00; failure_mode: Overheating; root_cause: Bearing lubrication degradation; corrective_action: Regrease bearing, inspect load current, clean cooling path; business_impact: Line speed reduction for 3 hours

Retrieved evidence:
1. maintenance_history.csv (motor/history): Historical maintenance record for MTR-204. Date: 2026-05-02 09:30:00. Issue: Motor temperature rising. Action: Cleaned cooling fins and checked bearing grease. Result: Temporary improvement. Downtime hours: 2.0.
2. failure_reports.csv (motor/failure report): Failure report for MTR-204. Date: 2026-04-18 07:45:00. Failure mode: Overheating. Root cause: Bearing lubrication degradation. Corrective action: Regrease bearing, inspect load current, clean cooling path. Business impact: Line speed reduction for 3 hours.
3. SOP_MTR_204_motor_overheating.txt (motor/overheating): Asset MTR-204 induction motor SOP. Symptoms: high winding temperature, rising current, vibration increase, repeated thermal alarms. Likely root causes: bearing lubrication loss, blocked cooling fins, overloaded drive, rotor imbalance. Inspection order: bearing
4. incident_records.csv (motor/incident): Incident record for MTR-204. Severity: High. Incident: Temperature crossed high alarm during peak load. Recommended response: Inspect bearing and cooling path.
5. delay_logs.csv (motor/delay): Delay log for MTR-204. Area: Hot Strip Mill. Delay hours: 3.5. Production impact or delay reason: Reduced motor load due to overheating.

**Previous Engineer Feedback Used**
- No matching records found.

**Agent Reasoning Trace**
- Triage Agent: Detected asset MTR-204 and equipment type Induction Motor.
- Sensor Agent: Failure risk 0.7778, anomaly level HIGH, RUL 1.0 days.
- Knowledge Agent: Retrieved 5 filtered evidence chunks.
- Risk Agent: Assigned P1 / CRITICAL.
- Planning Agent: Generated work order actions and spare strategy.
- Reporting Agent: Generated alert and logbook entry.

**LLM Engineer Explanation**
1. The asset is in a critical state requiring immediate attention.
2. The risk level is high, necessitating immediate action.
3. The hybrid failure risk is moderate, but the ML failure risk is low, making it less critical.

**Alert / Logbook Note**
- Alert: CRITICAL risk for MTR-204; Immediate action.
- Digital logbook entry created for follow-up.

TOOLS USED:
Asset: MTR-204
Priority: P1 - Immediate action
Anomaly: {'asset_id': 'MTR-204', 'anomaly_level': 'HIGH', 'hybrid_failure_risk': 0.7778, 'ml_failure_risk': 0.5063, 'operational_rule_score': 100.0, 'hybrid_health_score': 77.78, 'anomaly_events_24h': 24}
Alert: Alert for MTR-204: CRITICAL risk, P1, RUL 1.0 days.
LLM used: True
LLM validation: locked_fields_plus_llm_explanation
====================================================================================================
QUESTION: Create a P1 alert report for GBX-17 abnormal vibration.

ANSWER:

**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: GBX-17
- Equipment type: Gearbox
- Area: Finishing Mill
- Criticality: Critical
- Risk level: CRITICAL
- Priority: P1 - Immediate action
- Hybrid failure risk: 0.8218
- ML failure risk: 0.604
- Operational rule score: 100.0/100
- Hybrid health score: 82.18/100
- RUL / remaining useful life: 1.0 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: bearing wear, gear tooth wear, shaft misalignment, oil contamination, or foundation looseness.

**Risk Score Explanation**
- Gearbox vibration >= 7 mm/s: +30
- Gearbox vibration >= 9 mm/s: +20
- Gearbox vibration >= 10 mm/s: +10
- Gearbox temperature >= 65 deg C: +8
- Alarm count >= 2: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- Critical equipment: +15
- Historical delay impact 8.0 hours: +12.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.0794
- Vibration slope 24h: 0.0377
- Pressure slope 24h: -0.0093

**Immediate Actions**
- Check oil contamination and level.
- Inspect alignment, bearing condition, gear mesh, and foundation bolts.

**Spare Strategy**
- Gearbox bearing set: stock 1, lead time 12 days. Reserve before shutdown.
- Synthetic gear oil drum: stock 4, lead time 2 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1002; asset_id: GBX-17; timestamp: 2026-05-08 14:00:00; issue: Gearbox vibration above warning; action_taken: Oil sample collected, alignment checked; result: Bearing wear suspected; downtime_hours: 4.5

Failure reports:
- report_id: FR-202; asset_id: GBX-17; timestamp: 2026-04-26 18:10:00; failure_mode: High vibration; root_cause: Bearing pitting and gear mesh misalignment; corrective_action: Replace bearing set, verify coupling alignment; business_impact: Finishing mill delay risk

Retrieved evidence:
1. incident_records.csv (gearbox/incident): Incident record for GBX-17. Severity: Critical. Incident: Repeated vibration spikes during finishing load. Recommended response: Plan immediate vibration inspection.
2. failure_reports.csv (gearbox/failure report): Failure report for GBX-17. Date: 2026-04-26 18:10:00. Failure mode: High vibration. Root cause: Bearing pitting and gear mesh misalignment. Corrective action: Replace bearing set, verify coupling alignment. Business impact: Finishing mill delay risk.
3. maintenance_history.csv (gearbox/history): Historical maintenance record for GBX-17. Date: 2026-05-08 14:00:00. Issue: Gearbox vibration above warning. Action: Oil sample collected, alignment checked. Result: Bearing wear suspected. Downtime hours: 4.5.
4. SOP_GBX_17_gearbox_vibration.txt (gearbox/vibration): Asset GBX-17 gearbox SOP. Symptoms: vibration above 7 mm/s warning or above 9 mm/s critical, temperature rise, abnormal noise. Likely root causes: bearing pitting, gear mesh wear, coupling misalignment, oil contamination. Inspection order: vibration spectrum,
5. asset_health_summary.csv (gearbox/current health): Latest asset health for GBX-17. Risk band: CRITICAL. Hybrid failure risk: 0.8218. ML failure risk: 0.6039666217052109. Operational rule score: 100.0. Hybrid health score: 82.17849797673449. Estimated RUL days: 1.0. Temperature: 71.758. Vibration: 11.0. Pressur

**Previous Engineer Feedback Used**
- No matching records found.

**Agent Reasoning Trace**
- Triage Agent: Detected asset GBX-17 and equipment type Gearbox.
- Sensor Agent: Failure risk 0.8218, anomaly level HIGH, RUL 1.0 days.
- Knowledge Agent: Retrieved 5 filtered evidence chunks.
- Risk Agent: Assigned P1 / CRITICAL.
- Planning Agent: Generated work order actions and spare strategy.
- Reporting Agent: Generated alert and logbook entry.

**LLM Engineer Explanation**
1. The asset is in a critical risk level.
2. It has a high operational rule score.
3. There is a significant risk of hybrid failure.

**Alert / Logbook Note**
- Alert: CRITICAL risk for GBX-17; Immediate action.
- Digital logbook entry created for follow-up.

TOOLS USED:
Asset: GBX-17
Priority: P1 - Immediate action
Anomaly: {'asset_id': 'GBX-17', 'anomaly_level': 'HIGH', 'hybrid_failure_risk': 0.8218, 'ml_failure_risk': 0.604, 'operational_rule_score': 100.0, 'hybrid_health_score': 82.18, 'anomaly_events_24h': 24}
Alert: Alert for GBX-17: CRITICAL risk, P1, RUL 1.0 days.
LLM used: True
LLM validation: locked_fields_plus_llm_explanation
====================================================================================================
QUESTION: For PMP-09, check cavitation risk, spare availability, and maintenance plan.

ANSWER:

**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: PMP-09
- Equipment type: Cooling Water Pump
- Area: Caster Utility
- Criticality: High
- Risk level: CRITICAL
- Priority: P1 - Immediate action
- Hybrid failure risk: 0.7221
- ML failure risk: 0.5414
- Operational rule score: 87.0/100
- Hybrid health score: 72.21/100
- RUL / remaining useful life: 1.0 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: suction restriction, low tank level, air ingress, seal wear, or impeller wear; filter choking, relief valve drift, internal leakage, or pump wear.

**Risk Score Explanation**
- Pump pressure <= 6 bar: +22
- Pump vibration >= 5 mm/s: +12
- Alarm count >= 2: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- High criticality equipment: +10
- Historical delay impact 5.0 hours: +10.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.0029
- Vibration slope 24h: 0.015
- Pressure slope 24h: -0.0317

**Immediate Actions**
- Check suction strainer, tank level, air ingress, seal leakage, and impeller condition.

**Spare Strategy**
- Mechanical seal kit: stock 3, lead time 4 days. Reserve before shutdown.
- Impeller assembly: stock 1, lead time 10 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1003; asset_id: PMP-09; timestamp: 2026-05-14 11:15:00; issue: Pump cavitation noise; action_taken: Checked suction strainer and impeller clearance; result: Suction restriction found; downtime_hours: 3.0

Failure reports:
- report_id: FR-203; asset_id: PMP-09; timestamp: 2026-05-04 10:40:00; failure_mode: Cavitation; root_cause: Low suction head due to clogged strainer; corrective_action: Clean strainer, inspect impeller erosion; business_impact: Cooling instability risk

Retrieved evidence:
1. incident_records.csv (pump/incident): Incident record for PMP-09. Severity: High. Incident: Cavitation noise reported by operator. Recommended response: Check suction strainer and pump inlet.
2. spares_inventory.csv (pump/spares): Spare inventory for PMP-09. Part: Mechanical seal kit. Stock quantity: 3. Procurement lead time days: 4. Spare criticality: High. Unit cost INR: 22000.
3. maintenance_history.csv (pump/history): Historical maintenance record for PMP-09. Date: 2026-05-14 11:15:00. Issue: Pump cavitation noise. Action: Checked suction strainer and impeller clearance. Result: Suction restriction found. Downtime hours: 3.0.
4. failure_reports.csv (pump/failure report): Failure report for PMP-09. Date: 2026-05-04 10:40:00. Failure mode: Cavitation. Root cause: Low suction head due to clogged strainer. Corrective action: Clean strainer, inspect impeller erosion. Business impact: Cooling instability risk.
5. spares_inventory.csv (pump/spares): Spare inventory for PMP-09. Part: Impeller assembly. Stock quantity: 1. Procurement lead time days: 10. Spare criticality: Critical. Unit cost INR: 65000.

**Previous Engineer Feedback Used**
- No matching records found.

**Agent Reasoning Trace**
- Triage Agent: Detected asset PMP-09 and equipment type Cooling Water Pump.
- Sensor Agent: Failure risk 0.7221, anomaly level HIGH, RUL 1.0 days.
- Knowledge Agent: Retrieved 5 filtered evidence chunks.
- Risk Agent: Assigned P1 / CRITICAL.
- Planning Agent: Generated work order actions and spare strategy.
- Reporting Agent: Generated alert and logbook entry.

**LLM Engineer Explanation**
1. The asset is in a critical state requiring immediate attention.
2. The risk level is high, necessitating immediate action.
3. The hybrid failure risk is moderate, but the operational rule score indicates a high priority.

**Alert / Logbook Note**
- Alert: CRITICAL risk for PMP-09; Immediate action.
- Digital logbook entry created for follow-up.

TOOLS USED:
Asset: PMP-09
Priority: P1 - Immediate action
Anomaly: {'asset_id': 'PMP-09', 'anomaly_level': 'HIGH', 'hybrid_failure_risk': 0.7221, 'ml_failure_risk': 0.5414, 'operational_rule_score': 87.0, 'hybrid_health_score': 72.21, 'anomaly_events_24h': 24}
Alert: Alert for PMP-09: CRITICAL risk, P1, RUL 1.0 days.
LLM used: True
LLM validation: locked_fields_plus_llm_explanation
====================================================================================================
QUESTION: HPP-12 has low hydraulic pressure. Estimate RUL and generate work order.

ANSWER:

**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: HPP-12
- Equipment type: Hydraulic Power Pack
- Area: Plate Mill
- Criticality: Medium
- Risk level: CRITICAL
- Priority: P1 - Immediate action
- Hybrid failure risk: 0.7307
- ML failure risk: 0.536
- Operational rule score: 89.0/100
- Hybrid health score: 73.07/100
- RUL / remaining useful life: 1.3 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: filter choking, relief valve drift, internal leakage, or pump wear.

**Risk Score Explanation**
- Hydraulic pressure <= 6 bar: +25
- Hydraulic oil temperature >= 65 deg C: +10
- Hydraulic alarm count >= 2: +8
- Alarm count >= 2: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- Medium criticality equipment: +5
- Historical delay impact 4.0 hours: +8.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.0657
- Vibration slope 24h: 0.0026
- Pressure slope 24h: -0.0149

**Immediate Actions**
- Check filter differential pressure, oil contamination, relief valve setting, pump leakage, and actuator response.

**Spare Strategy**
- Hydraulic filter element: stock 6, lead time 3 days. Reserve before shutdown.
- Relief valve cartridge: stock 1, lead time 9 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1004; asset_id: HPP-12; timestamp: 2026-05-20 16:20:00; issue: Hydraulic pressure fluctuation; action_taken: Inspected relief valve and filter; result: Filter choking observed; downtime_hours: 2.5

Failure reports:
- report_id: FR-204; asset_id: HPP-12; timestamp: 2026-05-11 13:05:00; failure_mode: Low pressure; root_cause: Hydraulic oil leakage and filter choking; corrective_action: Replace filter, inspect seals, top up oil; business_impact: Actuator slow response

Retrieved evidence:
1. spares_inventory.csv (hydraulic/spares): Spare inventory for HPP-12. Part: Hydraulic filter element. Stock quantity: 6. Procurement lead time days: 3. Spare criticality: High. Unit cost INR: 8000.
2. failure_reports.csv (hydraulic/failure report): Failure report for HPP-12. Date: 2026-05-11 13:05:00. Failure mode: Low pressure. Root cause: Hydraulic oil leakage and filter choking. Corrective action: Replace filter, inspect seals, top up oil. Business impact: Actuator slow response.
3. maintenance_history.csv (hydraulic/history): Historical maintenance record for HPP-12. Date: 2026-05-20 16:20:00. Issue: Hydraulic pressure fluctuation. Action: Inspected relief valve and filter. Result: Filter choking observed. Downtime hours: 2.5.
4. spares_inventory.csv (hydraulic/spares): Spare inventory for HPP-12. Part: Relief valve cartridge. Stock quantity: 1. Procurement lead time days: 9. Spare criticality: Critical. Unit cost INR: 32000.
5. incident_records.csv (hydraulic/incident): Incident record for HPP-12. Severity: Medium. Incident: Pressure recovery slow after valve actuation. Recommended response: Inspect filter and relief valve.

**Previous Engineer Feedback Used**
- No matching records found.

**Agent Reasoning Trace**
- Triage Agent: Detected asset HPP-12 and equipment type Hydraulic Power Pack.
- Sensor Agent: Failure risk 0.7307, anomaly level HIGH, RUL 1.3 days.
- Knowledge Agent: Retrieved 5 filtered evidence chunks.
- Risk Agent: Assigned P1 / CRITICAL.
- Planning Agent: Generated work order actions and spare strategy.
- Reporting Agent: Generated alert and logbook entry.

**LLM Engineer Explanation**
1. The asset is in a critical state requiring immediate attention.
2. The risk level is high, necessitating immediate action.
3. The hybrid failure risk is moderate, but the ML failure risk is high, indicating a higher priority.

**Alert / Logbook Note**
- Alert: CRITICAL risk for HPP-12; Immediate action.
- Digital logbook entry created for follow-up.

TOOLS USED:
Asset: HPP-12
Priority: P1 - Immediate action
Anomaly: {'asset_id': 'HPP-12', 'anomaly_level': 'HIGH', 'hybrid_failure_risk': 0.7307, 'ml_failure_risk': 0.536, 'operational_rule_score': 89.0, 'hybrid_health_score': 73.07, 'anomaly_events_24h': 24}
Alert: Alert for HPP-12: CRITICAL risk, P1, RUL 1.3 days.
LLM used: True
LLM validation: locked_fields_plus_llm_explanation
====================================================================================================
QUESTION: Compare MTR-204, GBX-17, PMP-09, and HPP-12. Which equipment is most urgent today?

ANSWER:

**Plant-Level Maintenance Decision Summary**

**Locked Decision Fields**
- Most urgent asset: GBX-17
- Ranking basis: hybrid ML + operational rule score, criticality, delay severity, RUL, anomaly status, spares/procurement.

**Diagnosis**
- Plant equipment was compared across 4 demo steel assets.

**Root Cause**
- Priority is driven by degradation, production bottleneck impact, criticality, and maintenance constraints.

**Risk and RUL**
- GBX-17: P1/CRITICAL, hybrid score 82.18, ML risk 0.604, rule score 100.0, RUL 1.0 days, delay 8.0h
- MTR-204: P1/CRITICAL, hybrid score 77.78, ML risk 0.5063, rule score 100.0, RUL 1.0 days, delay 3.5h
- PMP-09: P1/CRITICAL, hybrid score 72.21, ML risk 0.5414, rule score 87.0, RUL 1.0 days, delay 5.0h

In [12]:
# ============================================================
# Cell 9: Feedback learning + real-time alert demo
# ============================================================

query = "MTR-204 temperature and current are high. Give root cause and maintenance plan."
result = maintenance_agent(query, user_id="maintenance_engineer_01")

feedback_row = save_feedback(
    user_id="maintenance_engineer_01",
    asset_id=result["asset_id"],
    query=query,
    feedback_type="accepted",
    feedback_text="Recommendation accepted. Inspect bearing lubrication first.",
    corrected_action="Inspect bearing lubrication first, then verify cooling airflow and current imbalance.",
    outcome="Pending inspection",
)

print("Feedback saved:")
print(feedback_row)

print("\nRe-running same query to show feedback is reused:")
result2 = maintenance_agent(query, user_id="maintenance_engineer_01")
print(result2["answer"][:1800])

print("\nReal-time alert simulation:")
alert_result = ingest_new_sensor_alert(
    asset_id="GBX-17",
    temperature=72.5,
    vibration=10.4,
    current=74.0,
    pressure=7.6,
    alarm_count=4,
)
print(alert_result["answer"][:1800])

print("\nDigital logbook:")
display(pd.read_csv(f"{DATA_DIR}/digital_logbook.csv").tail())

print("\nFeedback log:")
display(pd.read_csv(f"{DATA_DIR}/feedback_log.csv").tail())

Feedback saved:
{'timestamp': '2026-06-08T14:21:30.199437', 'user_id': 'maintenance_engineer_01', 'asset_id': 'MTR-204', 'query': 'MTR-204 temperature and current are high. Give root cause and maintenance plan.', 'feedback_type': 'accepted', 'feedback_text': 'Recommendation accepted. Inspect bearing lubrication first.', 'corrected_action': 'Inspect bearing lubrication first, then verify cooling airflow and current imbalance.', 'outcome': 'Pending inspection'}

Re-running same query to show feedback is reused:
**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: MTR-204
- Equipment type: Induction Motor
- Area: Hot Strip Mill
- Criticality: High
- Risk level: CRITICAL
- Priority: P1 - Immediate action
- Hybrid failure risk: 0.7778
- ML failure risk: 0.5063
- Operational rule score: 100.0/100
- Hybrid health score: 77.78/100
- RUL / remaining useful life: 1.0 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: bearing lubrication degradation, cooling restriction, overload, or current imbalance.

**Risk Score Explanation**
- Motor temperature >= 80 deg C: +25
- Motor temperature >= 85 deg C: +15
- Motor current >= 80 A: +12
- Motor vibration >= 5 mm/s: +8
- Alarm count >= 2: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- High criticality equipment: +10
- Historical delay impact 3.5 hours: +7.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.1833
- Vibration slope 24h: 0.0158
- Pressure slope 24h: -0.0065

**Immediate Actions**
- Apply learned feedback: inspect bearing lubrication first.
- Inspect bearing lubrication, cooling airflow, current imbalance, load, and coupling alignment.

**Spare Strategy**
- DE bearing 6312: stock 2, lead time 5 days. Reserve before shutdown.
- Cooling fan kit: stock 1, lead time 7 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1001; asset_id: MTR-204; timestamp: 2026-05-02 09:30:00; issue: Motor temperature rising; action_taken:

Real-time alert simulation:
**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: GBX-17
- Equipment type: Gearbox
- Area: Finishing Mill
- Criticality: Critical
- Risk level: HIGH
- Priority: P2 - Action within 24 hours
- Hybrid failure risk: 0.6098
- ML failure risk: 0.133
- Operational rule score: 100.0/100
- Hybrid health score: 60.98/100
- RUL / remaining useful life: 2.8 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: bearing wear, gear tooth wear, shaft misalignment, oil contamination, or foundation looseness.

**Risk Score Explanation**
- Gearbox vibration >= 7 mm/s: +30
- Gearbox vibration >= 9 mm/s: +20
- Gearbox vibration >= 10 mm/s: +10
- Gearbox temperature >= 65 deg C: +8
- Alarm count >= 2: +8
- Alarm count >= 4: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- Critical equipment: +15
- Historical delay impact 8.0 hours: +12.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.1143
- Vibration slope 24h: 0.0335
- Pressure slope 24h: -0.032

**Immediate Actions**
- Check oil contamination and level.
- Inspect alignment, bearing condition, gear mesh, and foundation bolts.

**Spare Strategy**
- Gearbox bearing set: stock 1, lead time 12 days. Reserve before shutdown.
- Synthetic gear oil drum: stock 4, lead time 2 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1002; asset_id: GBX-17; timestamp: 2026-05-08 14:00:00; issue: Gearbox vibration above warning; action_taken:

Digital logbook:

,timestamp,user,asset_id,log_entry,status,user_id,query,risk_level,priority,summary
8,2026-06-08T14:21:19.446608,NaN,GBX-17,NaN,NaN,demo_user,"Compare MTR-204, GBX-17, PMP-09, and HPP-12. W...",PLANT_SUMMARY,PLANT,**Plant-Level Maintenance Decision Summary**\n...
9,2026-06-08T14:21:23.904902,NaN,GBX-17,NaN,NaN,demo_user,"For the same asset, what spare should I arrang...",CRITICAL,P1,**Maintenance Wizard Report**\n\n**Locked Deci...
10,2026-06-08T14:21:30.195076,NaN,MTR-204,NaN,NaN,maintenance_engineer_01,MTR-204 temperature and current are high. Give...,CRITICAL,P1,**Maintenance Wizard Report**\n\n**Locked Deci...
11,2026-06-08T14:21:36.469480,NaN,MTR-204,NaN,NaN,maintenance_engineer_01,MTR-204 temperature and current are high. Give...,CRITICAL,P1,**Maintenance Wizard Report**\n\n**Locked Deci...
12,2026-06-08T14:21:41.802406,NaN,GBX-17,NaN,NaN,iot_gateway,New real-time alert for GBX-17. Diagnose and g...,HIGH,P2,**Maintenance Wizard Report**\n\n**Locked Deci...

Feedback log:

,timestamp,user,asset_id,query,recommendation,engineer_feedback,outcome,user_id,feedback_type,feedback_text,corrected_action
0,2026-06-08T14:21:30.199437,NaN,MTR-204,MTR-204 temperature and current are high. Give...,NaN,NaN,Pending inspection,maintenance_engineer_01,accepted,Recommendation accepted. Inspect bearing lubri...,"Inspect bearing lubrication first, then verify..."

In [13]:
# ============================================================
# Cell 10: Performance, ranking, explanation test
# Fixed:
# - No dependency on old sensor_logs.csv
# - Tests real-time alert scoring consistency
# - Tests public AI4I governance response
# ============================================================

test_cases = [
    "MTR-204 has high temperature and abnormal current. Diagnose, give RUL, risk, spares, and sources.",
    "GBX-17 has abnormal vibration. Give root cause, priority, work order, spares, and alert.",
    "PMP-09 has cavitation symptoms. Give maintenance plan and procurement strategy.",
    "HPP-12 has low hydraulic pressure. Give RUL, root cause, and immediate action.",
    "Compare all equipment and tell supervisor what to prioritize today.",
    "For the same asset, what spare should I arrange next?",
    "What public dataset was used and how is it connected to the steel maintenance demo?",
]

required_words = [
    "diagnosis",
    "root cause",
    "risk",
    "rul",
    "action",
    "spare",
    "source",
    "alert",
    "agent reasoning trace",
]

exact_checks = [
    "Risk level:",
    "Priority:",
    "RUL / remaining useful life:",
    "Hybrid failure risk:",
    "ML failure risk:",
    "Operational rule score:",
    "Risk Score Explanation",
]

rows = []

for q in test_cases:
    start = time.time()
    result = maintenance_agent(q)
    latency = time.time() - start
    answer = result.get("answer", "")
    text = answer.lower()

    keyword_hits = sum(1 for w in required_words if w in text)
    exact_hits = sum(1 for w in exact_checks if w.lower() in text)

    if "public dataset" in q.lower() or "ai4i" in q.lower():
        public_ok = int(
            ("ai4i" in text or "uci" in text)
            and ("leakage" in text or "target" in text)
            and ("separate" in text or "steel" in text)
        )
        score = round(100 * public_ok, 2)
    else:
        public_ok = 1
        score = round(
            100 * (
                0.60 * keyword_hits / len(required_words)
                + 0.30 * exact_hits / len(exact_checks)
                + 0.10 * public_ok
            ),
            2,
        )

    rows.append({
        "query": q,
        "asset_id": result.get("asset_id"),
        "score": score,
        "latency_sec": round(latency, 2),
        "llm_used": result.get("llm_used"),
        "llm_validation": result.get("llm_validation"),
        "answer_preview": answer[:700],
    })

test_df = pd.DataFrame(rows)
test_df.to_csv(f"{REPORT_DIR}/cell10_requirement_scores.csv", index=False)

plant = maintenance_agent("Compare all equipment and tell supervisor what to prioritize today.")
plant_df = pd.DataFrame(plant.get("plant_priority_table", []))

top_asset = plant_df.iloc[0]["asset_id"] if len(plant_df) else None
ranking_ok = top_asset in ["GBX-17", "MTR-204", "PMP-09", "HPP-12"]

public_path = f"{DATA_DIR}/public_ai4i_common_schema.csv"
steel_path = f"{DATA_DIR}/steel_sensor_logs.csv"

public_dataset_rows = len(pd.read_csv(public_path)) if os.path.exists(public_path) else 0
demo_steel_rows = len(pd.read_csv(steel_path)) if os.path.exists(steel_path) else 0

# Real-time alert consistency check
alert_result = ingest_new_sensor_alert(
    asset_id="GBX-17",
    temperature=72.5,
    vibration=10.4,
    current=74.0,
    pressure=7.6,
    rpm=980,
    alarm_count=4,
)

alert_answer = alert_result.get("answer", "")
alert_sensor = alert_result.get("sensor_summary", {})
alert_consistency_ok = (
    alert_sensor.get("hybrid_health_score", 0) >= 75
    and "Risk level: CRITICAL" in alert_answer
    and "Operational rule score:" in alert_answer
)

summary = {
    "average_requirement_score": round(float(test_df["score"].mean()), 2),
    "average_latency_sec": round(float(test_df["latency_sec"].mean()), 2),
    "top_priority_asset": top_asset,
    "ranking_ok": bool(ranking_ok),
    "public_dataset_rows": int(public_dataset_rows),
    "demo_steel_rows": int(demo_steel_rows),
    "public_dataset_used": bool(public_dataset_rows > 0),
    "ai4i_leakage_removed": True,
    "app_decision_score": "hybrid ML + operational rules",
    "risk_labeling": "hybrid_failure_risk shown separately from ml_failure_risk",
    "rule_breakdown_enabled": True,
    "real_time_alert_consistency_ok": bool(alert_consistency_ok),
    "real_time_alert_asset": alert_result.get("asset_id"),
    "real_time_alert_priority": alert_result.get("priority"),
    "real_time_alert_hybrid_score": alert_sensor.get("hybrid_health_score"),
    "steel_threshold": float(STEEL_THRESHOLD),
    "public_threshold": float(PUBLIC_THRESHOLD),
}

Path(f"{REPORT_DIR}/cell10_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

print(json.dumps(summary, indent=2))
display(test_df)

print("\nPlant priority table:")
display(plant_df.head(12))

print("\nReal-time alert consistency preview:")
print(alert_answer[:1800])

print("\nSample GBX-17 rule breakdown:")
gbx = maintenance_agent("GBX-17 has abnormal vibration. Give root cause, priority, work order, spares, and alert.")
for item in gbx.get("rule_breakdown", []):
    print("-", item)

{
  "average_requirement_score": 95.71,
  "average_latency_sec": 5.8,
  "top_priority_asset": "MTR-204",
  "ranking_ok": true,
  "public_dataset_rows": 10000,
  "demo_steel_rows": 2881,
  "public_dataset_used": true,
  "ai4i_leakage_removed": true,
  "app_decision_score": "hybrid ML + operational rules",
  "risk_labeling": "hybrid_failure_risk shown separately from ml_failure_risk",
  "rule_breakdown_enabled": true,
  "real_time_alert_consistency_ok": true,
  "real_time_alert_asset": "GBX-17",
  "real_time_alert_priority": "P1 - Immediate action",
  "real_time_alert_hybrid_score": 78.96,
  "steel_threshold": 0.04382305057411851,
  "public_threshold": 0.545928313124836
}

,query,asset_id,score,latency_sec,llm_used,llm_validation,answer_preview
0,MTR-204 has high temperature and abnormal curr...,MTR-204,100.0,6.20,True,locked_fields_plus_llm_explanation,**Maintenance Wizard Report**\n\n**Locked Deci...
1,GBX-17 has abnormal vibration. Give root cause...,GBX-17,100.0,4.71,True,locked_fields_plus_llm_explanation,**Maintenance Wizard Report**\n\n**Locked Deci...
2,PMP-09 has cavitation symptoms. Give maintenan...,PMP-09,100.0,5.80,True,locked_fields_plus_llm_explanation,**Maintenance Wizard Report**\n\n**Locked Deci...
3,"HPP-12 has low hydraulic pressure. Give RUL, r...",HPP-12,100.0,6.21,True,locked_fields_plus_llm_explanation,**Maintenance Wizard Report**\n\n**Locked Deci...
4,Compare all equipment and tell supervisor what...,MTR-204,70.0,11.49,True,locked_fields_plus_llm_explanation,**Plant-Level Maintenance Decision Summary**\n...
5,"For the same asset, what spare should I arrang...",MTR-204,100.0,6.12,True,locked_fields_plus_llm_explanation,**Maintenance Wizard Report**\n\n**Locked Deci...
6,What public dataset was used and how is it con...,PUBLIC_AI4I,100.0,0.04,True,dataset_governance_summary,**Public Dataset and ML Validation Summary**\n...

Plant priority table:

,asset_id,asset_type,area,criticality,ml_failure_risk,hybrid_failure_risk,operational_rule_score,hybrid_health_score,rul_days,risk_level,priority,priority_score,urgency,delay_hours
0,MTR-204,Induction Motor,Hot Strip Mill,High,0.5063,0.7778,100.0,77.78,1.0,CRITICAL,P1,88.03,Immediate action,3.5
1,PMP-09,Cooling Water Pump,Caster Utility,High,0.5414,0.7221,87.0,72.21,1.0,CRITICAL,P1,84.71,Immediate action,5.0
2,HPP-12,Hydraulic Power Pack,Plate Mill,Medium,0.5360,0.7307,89.0,73.07,1.3,CRITICAL,P1,84.07,Immediate action,4.0
3,GBX-17,Gearbox,Finishing Mill,Critical,0.1330,0.6098,100.0,60.98,2.8,HIGH,P2,73.98,Action within 24 hours,8.0

Real-time alert consistency preview:
**Maintenance Wizard Report**

**Locked Decision Fields**
- Asset ID: GBX-17
- Equipment type: Gearbox
- Area: Finishing Mill
- Criticality: Critical
- Risk level: CRITICAL
- Priority: P1 - Immediate action
- Hybrid failure risk: 0.7896
- ML failure risk: 0.5324
- Operational rule score: 100.0/100
- Hybrid health score: 78.96/100
- RUL / remaining useful life: 1.0 days

**Diagnosis**
- The asset shows HIGH abnormality based on sensor trend, anomaly events, ML signal, and operational safety rules.

**Root Cause**
- Probable root cause: bearing wear, gear tooth wear, shaft misalignment, oil contamination, or foundation looseness.

**Risk Score Explanation**
- Gearbox vibration >= 7 mm/s: +30
- Gearbox vibration >= 9 mm/s: +20
- Gearbox vibration >= 10 mm/s: +10
- Gearbox temperature >= 65 deg C: +8
- Alarm count >= 2: +8
- Alarm count >= 4: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- Critical equipment: +15
- Historical delay impact 8.0 hours: +12.0

**Risk and RUL Explanation**
- Final app decision uses hybrid scoring: 0.45 * ML failure risk + 0.55 * operational rule score.
- RUL is reduced by hybrid failure risk, anomaly count, criticality, and degradation slope.
- Temperature slope 24h: 0.1278
- Vibration slope 24h: 0.0234
- Pressure slope 24h: -0.0526

**Immediate Actions**
- Check oil contamination and level.
- Inspect alignment, bearing condition, gear mesh, and foundation bolts.

**Spare Strategy**
- Gearbox bearing set: stock 1, lead time 12 days. Reserve before shutdown.
- Synthetic gear oil drum: stock 4, lead time 2 days. Reserve before shutdown.

**Evidence / Sources**
Historical work orders:
- work_order_id: WO-1002; asset_id: GBX-17; timestamp: 2026-05-08 14:00:00; issue: Gearbox vibration above warning; action_taken:

Sample GBX-17 rule breakdown:
- Gearbox vibration >= 7 mm/s: +30
- Gearbox vibration >= 9 mm/s: +20
- Gearbox vibration >= 10 mm/s: +10
- Gearbox temperature >= 65 deg C: +8
- Alarm count >= 2: +8
- Alarm count >= 4: +8
- Anomaly events >= 6 in last 24h: +15
- Anomaly events >= 18 in last 24h: +10
- Critical equipment: +15
- Historical delay impact 8.0 hours: +12.0